---
# Lint directives.
lint:
  # Linter rules.
  # Run `protolint list` to see all available rules.
  rules:
    # Determines whether or not to include the default set of linters.
    no_default: true

    # Set the default to all linters. This option works the other way around as no_default does.
    # If you want to enable this option, delete the comment out below and no_default.
    # all_default: true

    # The specific linters to add.
    add:
      - SERVICE_NAMES_END_WITH
      - ORDER
      - PROTO3_FIELDS_AVOID_REQUIRED
      - PROTO3_GROUPS_AVOID
      - SYNTAX_CONSISTENT
      - RPC_NAMES_CASE
      - QUOTE_CONSISTENT

    # The specific linters to remove.
    remove: []
