syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "alliance_banner.proto";
import "authorization.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
import "player.proto";
import "player_search.proto";
import "uuid.proto";

enum AllianceAdmissionType {
  AllianceAdmissionType_OPEN = 0;
  AllianceAdmissionType_CLOSED = 1;
  AllianceAdmissionType_REQUEST = 2;
}

enum AlliancePlaystyleType {
  AlliancePlaystyleType_ALL = 0;
  AlliancePlaystyleType_BEGINNER = 1;
  AlliancePlaystyleType_CASUAL = 2;
  AlliancePlaystyleType_COMPETITIVE = 3;
}

enum AllianceApplicationType {
  AllianceApplicationType_REQUEST = 0;
  AllianceApplicationType_INVITE = 1;
}

enum AllianceApplicationState {
  AllianceApplicationState_NONE = 0;
  AllianceApplicationState_ACTIVE = 1;
  AllianceApplicationState_ACCEPTED = 2;
  AllianceApplicationState_REJECTED = 3;
  AllianceApplicationState_CANCELED = 4;
  AllianceApplicationState_DELETED = 5;
  AllianceApplicationState_DISMISSED = 6;
}

message AllianceConfigurationDefinitionDTO {
  string definition_id = 1;
  int32 max_members_count = 2;
  google.protobuf.Duration cost = 6;
  google.protobuf.Duration rejoin_timeout = 7;
  google.protobuf.Duration application_timeout = 8;
}

message SearchAllianceRequest {
  string search = 3;
  bool refresh = 6;
  AlliancePlaystyleType playstyle = 7;
  AllianceAdmissionType admission = 8;
  string locale = 9;
  int32 min_free_slots = 10;
}

message SuggestAllianceRequest {
  bool refresh = 1;
  AlliancePlaystyleType playstyle = 2;
  AllianceAdmissionType admission = 3;
  string locale = 4;
}

message SearchAllianceResponse {
}

message AllianceInfoRequest {
  int64 alliance_id = 1;
}

message AllianceDTO {
  int64 alliance_id = 1;
  int32 members_count = 2;
  AllianceSettingsDTO settings = 4;
  int32 rank = 6;
  int32 max_members = 7;
}

message AllianceWithLeaderDTO {
  AllianceDTO alliance = 1;
  AllianceMemberDTO leader = 2;
  bool has_applied = 3;
}

message AllianceSearchResultDTO {
  AllianceDTO alliance = 1;
  AllianceMemberDTO leader = 2;
  bool has_applied = 3;
  int64 score = 4;
}

message AllianceSettingsDTO {
  string name = 1;
  string description = 2;
  string locale = 4;
  AllianceAdmissionType admission = 5;
  AlliancePlaystyleType playstyle = 8;
  string required_age = 9;
  int32 required_total_power = 10;
  int32 required_treasure_hunt_difficulty = 11;
  AllianceBannerDTO banner = 12;
}

message AllianceKickRequest {
  int32 target_player_id = 1;
}

message AllianceChangeRoleRequest {
  int32 target_player_id = 1;
  string target_role_definition_id = 2;
}

message AllianceChangeSettingsRequest {
  string description = 1;
  AllianceAdmissionType admission = 2;
  string locale = 3;
  string name = 4;
  AlliancePlaystyleType playstyle = 7;
  string required_age = 8;
  int32 required_total_power = 9;
  int32 required_treasure_hunt_difficulty = 10;
  AllianceBannerDTO banner = 11;
}

message AllianceCreateRequest {
  AllianceChangeSettingsRequest settings = 1;
}

message AllianceJoinRequest {
  int64 alliance_id = 1;
}

message AllianceHopRequest {
  int64 alliance_id = 1;
}

message AllianceMembersRequest {
  int64 alliance_id = 1;
}

message AllianceMembersResponse {
  int64 alliance_id = 1;
}

message AllianceMemberDTO {
  RoleDefinitionDTO role = 2;
  int64 last_seen_online_in_seconds = 6;
  PlayerInfoDTO player_profile = 7;
  int64 points = 8;
  google.protobuf.Timestamp joined_at = 10;
}

message AlliancePlayerDTO {
  int32 player_id = 1;
  string name = 2;
}

message AlliancePush {
  UUID uuid = 1;
  AllianceDTO alliance = 2;
}

message AlliancePlayerAddedPush {
  int64 alliance_id = 1;
  AllianceMemberDTO member = 2;
}

message AllianceMemberUpdatedPush {
  AllianceMemberDTO member = 1;
}

message AlliancePlayerRemovedPush {
  int64 alliance_id = 1;
  int32 player_id = 2;
}

message AlliancePlayerNotInAlliancePush {
}

message AllianceAccountPush {
  int64 alliance_id = 1;
  int32 player_id = 2;
  RoleDefinitionDTO role = 3;
}

message AllianceBroadcastStatePush {
  int64 alliance_id = 1;
  google.protobuf.Timestamp last_broadcast_sent_at = 2;
}

message AllianceApplyApplicationRequest {
  int64 alliance_id = 1;
  string text = 2;
}

message AllianceAcceptApplicationRequest {
  int32 target_player_id = 1;
}

message AllianceRejectApplicationRequest {
  int32 target_player_id = 1;
  string response_text = 2;
}

message AllianceCancelApplicationRequest {
  int64 alliance_id = 1;
}

message AllianceDismissApplicationRequest {
  int64 alliance_id = 1;
}

message AllianceInviteRequest {
  int64 alliance_id = 1;
  int32 invited_player_id = 2;
  string text = 3;
}

message AllianceAcceptInvitationRequest {
  int64 alliance_id = 1;
}

message AllianceRejectInvitationRequest {
  int32 invited_player_id = 1;
  int64 alliance_id = 2;
  string response_text = 3;
}

message AllianceCancelInvitationRequest {
  int32 invited_player_id = 1;
  int64 alliance_id = 2;
}

message AllianceApplicationDTO {
  PlayerInfoDTO applying_player = 1;
  string text = 2;
  int64 application_id = 3;
}

message AllianceApplicationPushDTO {
  int64 alliance_id = 1;
  string text = 3;
  AllianceApplicationState state = 4;
  AllianceApplicationType type = 5;
  AllianceWithLeaderDTO alliance_with_leader = 6;
  PlayerInfoDTO inviting_player = 7;
  google.protobuf.Timestamp created_at = 8;
  google.protobuf.Timestamp rejected_at = 9;
  bool dismissed = 10;
  PlayerSearchEntryDTO applying_player_detailed = 11;
  string rejection_text = 12;
  int64 application_id = 13;
}

message InboxKickedDTO {
  InboxAllianceDTO alliance = 1;
  PlayerInfoDTO kicked_player = 2;
}

message InboxAllianceDTO {
  int64 alliance_id = 1;
  string name = 2;
}

message ChatStickerDefinitionDTO {
  string id = 1;
  string asset_id = 2;
  bool unlocked_by_default = 3;
}

message ChatStickerUnlockedPush {
}

message ChatGlobalMessage {
  string headline_loca_key = 1;
  string text_loca_key = 2;
}

message ChatJoinedMessage {
  PlayerInfoDTO player = 1;
}

message ChatLeftMessage {
  PlayerInfoDTO player = 1;
}

message ChatKickedMessage {
  PlayerInfoDTO kicking_player = 1;
  PlayerInfoDTO kicked_player = 2;
}

message ChatRoleChangedMessage {
  PlayerInfoDTO changing_player = 1;
  PlayerInfoDTO changed_player = 2;
  string new_role_definition_id = 3;
  string old_role_definition_id = 4;
}

message ChatRoleChangedBySystemMessage {
  PlayerInfoDTO changed_player = 1;
  string new_role_definition_id = 2;
  string old_role_definition_id = 3;
}

message ChatSettingsChangedMessage {
  PlayerInfoDTO player = 1;
  AllianceSettingsDTO old_settings = 2;
  AllianceSettingsDTO new_settings = 3;
}

message ChatCreatedAllianceMessage {
  PlayerInfoDTO player = 1;
  InboxAllianceDTO new_alliance = 2;
}

message ChatJoinedAllianceMessage {
  PlayerInfoDTO player = 1;
  InboxAllianceDTO new_alliance = 2;
}

message ChatJoinAllianceMessage {
}

message AlliancePlayerJoinedChatNotificationDTO {
  int32 player_id = 1;
}

message AlliancePlayerLeftChatNotificationDTO {
  int32 player_id = 1;
  bool was_kicked = 2;
  int32 kicked_by_player_id = 3;
}

message AlliancePlayerRoleChangedChatNotificationDTO {
  int32 player_id = 1;
  int32 target_player_id = 2;
  string old_role_definition_id = 3;
  string new_role_definition_id = 4;
}

message AllianceSettingsChangedChatNotificationDTO {
  int32 player_id = 1;
}

message AllianceKickPlayerNotificationDTO {
  AllianceInfoDTO alliance_info = 1;
}

message AllianceInfoDTO {
  int64 alliance_id = 1;
  string name = 2;
  int32 member_count = 5;
  AllianceBannerDTO banner = 6;
}

message AllianceBroadcastNotificationDTO {
  string message = 1;
  int32 sender_player_id = 2;
}

message SendAllianceBroadcastRequest {
  string message = 1;
}
