syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/timestamp.proto";

enum AnnouncementType {
  AnnouncementType_EVENT = 0;
  AnnouncementType_INFO = 1;
}

message AnnouncementDTO {
  int32 id = 1;
  string asset_id = 2;
  google.protobuf.Timestamp announced_at = 3;
  AnnouncementType type = 4;
  google.protobuf.Timestamp platforms = 5;
  google.protobuf.Timestamp valid_from = 6;
  google.protobuf.Timestamp valid_until = 7;
  string gift_definition_id = 8;
  bool priority = 9;
  bool show_badge_notification = 10;
  string banner_asset_id = 11;
  string image_asset_id = 12;
  bool image_above_text = 13;
  string locales = 15;
  string fallback_locale = 16;
}

message AnnouncementGiftCollectedDTO {
}

message AnnouncementLocaleDTO {
  string header = 1;
  string description = 2;
  string body = 3;
  string button_text = 4;
  string button_link = 5;
  string locale = 6;
}

message TargetFilterValueDTO {
  string type = 1;
  string value = 2;
}

message AnnouncementDeletionDTO {
  int64 id = 1;
}
