syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "construction.proto";
import "expansion_type.proto";
import "google/protobuf/timestamp.proto";
import "hero_battle.proto";
import "init.proto";
import "upgrade.proto";
import "uuid.proto";
import "worker.proto";

enum CollectType {
  CollectionType_ALL = 0;
  CollectionType_BUILDING = 1;
  CollectionType_CUSTOMIZATION = 2;
}

enum BuildingRotationType {
  BuildingRotationType_ROTATION_0 = 0;
  BuildingRotationType_ROTATION_90 = 1;
}

message BuildingDefinitionDTO {
  string id = 1;
  string type = 2;
  int32 width = 3;
  int32 height = 4;
  int32 components = 5;
  int32 cities = 7;
  int32 free_production_slots = 8;
  string age = 9;
  string group = 10;
  HappinessEffectDTO happiness_effect = 11;
  int32 level = 12;
  ExpansionSubType expansion_sub_type = 14;
  string asset_id = 15;
}

message IncreaseResourceCapacityComponentDTO {
  string resource = 1;
  int32 capacity = 2;
}

message SellComponentDTO {
  string id = 1;
  ActionComponentDTO start = 2;
  bool for_inventory = 3;
  bool keep_level = 4;
}

message MoveComponentDTO {
  string id = 1;
}

message BuildingDTO {
  BuildingIdDTO id = 1;
  string definition_id = 2;
  int32 x = 4;
  int32 y = 5;
  ConstructionDTO productions = 6;
  ConstructionDTO construction = 7;
  BuildingRotationType rotation = 9;
  UpgradeDTO upgrade = 10;
  int32 slots = 11;
  int32 bought_slots = 12;
  int64 city_id = 13;
  string customization_definition_id = 15;
  google.protobuf.Timestamp customization_applied_at = 16;
  string age = 17;
  int32 level = 18;
  int32 produced_happiness = 19;
  bool is_rebuild = 20;
  bool happiness_changes = 21;
  bool restart_production_after_upgrade = 22;
  string linked_expansion_definition_id = 23;
}

message HappinessChangeDTO {
  google.protobuf.Timestamp at = 1;
  int32 change = 2;
}

message BuildingIdDTO {
  UUID id = 1;
}

message BuildingHappinessUpdateDTO {
  BuildingIdDTO building_id = 1;
}

message GetBuildingRequest {
  BuildingIdDTO building_id = 1;
}

message SyncBuildingRequest {
  BuildingIdDTO building_id = 1;
}

message GetAffectedBuildingRequest {
  BuildingIdDTO building_id = 1;
}

message StartConstructionRequest {
  int64 city_id = 1;
  string definition_id = 2;
  int32 x = 3;
  int32 y = 4;
  BuildingRotationType rotation = 5;
  BuildingIdDTO building_id = 7;
  bool reserved_worker_ids = 8;
  bool from_inventory = 9;
}

message StartConstructionResponse {
  BuildingDTO building = 1;
}

message FinishConstructionRequest {
  BuildingIdDTO building_id = 1;
}

message SkipConstructionRequest {
  BuildingIdDTO building_id = 1;
}

message QueueMultipleProductionsRequest {
}

message QueueProductionRequest {
  BuildingIdDTO building_id = 1;
  string definition_id = 2;
}

message CancelProductionRequest {
  BuildingIdDTO building_id = 1;
  int32 slot = 2;
}

message SkipProductionRequest {
  BuildingIdDTO building_id = 1;
  int32 slot = 2;
  bool cancel_queued = 3;
}

message CollectProductionsRequest {
  CollectType buildings = 1;
  CollectType type = 3;
}

message CollectWorkerProductionRequest {
  BuildingIdDTO building_id = 1;
  int32 slot = 2;
}

message MultiMoveBuildingRequest {
}

message MoveBuildingRequest {
  BuildingIdDTO building_id = 1;
  int32 x = 2;
  int32 y = 3;
  BuildingRotationType rotation = 6;
}

message SellBuildingRequest {
  BuildingIdDTO building_id = 1;
}

message StartUpgradeRequest {
  BuildingIdDTO building_id = 1;
  bool reserved_worker_ids = 3;
  bool restart_production_after_upgrade = 4;
}

message FinishUpgradeRequest {
  BuildingIdDTO building_id = 1;
}

message SkipUpgradeRequest {
  BuildingIdDTO building_id = 1;
}

message UnlockNextProductionSlotRequest {
  BuildingIdDTO building_id = 1;
}

message UnlockableProductionSlotDTO {
  ActionComponentDTO start = 1;
  int32 order = 2;
}

message CancellationPeriodRequirementDTO {
  int32 cancellation_period = 1;
}

message HappinessEffectDTO {
  int32 max_happiness = 1;
  double effect = 2;
}

message CultureComponentDTO {
  string id = 1;
  int32 range = 2;
  int32 points = 3;
  string dynamic_points_definition_id = 4;
  string dynamic_range_definition_id = 5;
}

message PinnedAgeComponentDTO {
  string id = 1;
}

message GrantWorkerComponentDTO {
  string id = 1;
  int32 amount = 2;
  WorkerType type = 3;
  string dynamic_amount_definition_id = 4;
}

message BuildingPinnedAgeDTO {
  string building_definition_id = 1;
  string age_definition_id = 2;
}

message BuildingNextLevelDTO {
  string building_definition_id = 1;
  int32 level = 2;
}

message BuildingProductionLocationDTO {
  BuildingIdDTO building_id = 1;
}

message BuildingUnitProviderComponentDTO {
  HeroUnitDTO unit = 1;
}

message SubscriptionSlotComponentDTO {
  string subscription_benefit_definition_id = 1;
  int32 slots = 2;
}
