syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "building.proto";
import "google/protobuf/duration.proto";
import "init.proto";

message BuildingCustomizationDefinitionDTO {
  string id = 1;
  google.protobuf.Duration duration = 2;
  string building_group = 3;
  int32 components = 4;
  int32 order = 6;
  string city_definition_id = 7;
}

message CustomizationCollectionDefinitionDTO {
  string id = 1;
  ActionComponentDTO customization_definition_ids = 2;
  ActionComponentDTO complete = 3;
}

message CustomizationCollectionDTO {
  string definition_id = 1;
  bool collected = 2;
}

message BuildingCustomizationRewardDTO {
  string definition = 1;
  int32 amount = 2;
  string id = 3;
}

message CultureBoostComponentDTO {
  string id = 1;
  double culture_boost = 2;
}

message OriginComponentDTO {
  string id = 1;
  string type = 3;
  string name = 4;
  int32 order = 5;
}

message ApplyCustomizationRequest {
  BuildingIdDTO building_id = 1;
  string definition_id = 2;
}

message CollectCustomizationCollectionRequest {
  string definition_id = 1;
}
