syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "construction.proto";
import "expansion_type.proto";
import "expansion_unlocking_type.proto";
import "init.proto";
import "resource.proto";
import "uuid.proto";

message CityDefinitionDTO {
  string id = 1;
  CityInitDefinitionDTO components = 2;
  CityInitDefinitionDTO city_init_definition = 3;
  int32 soft_currency_resource_definitions = 5;
  int32 order = 6;
  string asset_id = 7;
  bool can_visit = 8;
}

message CityInitDefinitionDTO {
  string id = 1;
}

message CityListDTO {
}

message CityDTO {
  int64 id = 1;
  string definition_id = 2;
  string name = 3;
  BuildingLimitsDTO workers = 5;
  BuildingLimitsDTO grid = 6;
  BuildingLimitsDTO building_limits = 7;
  ExpansionInfoDTO expansion_info = 8;
}

message UnlockedCityDTO {
  int64 id = 1;
  string definition_id = 2;
  BuildingLimitsDTO building_limits = 3;
}

message GridAreaDTO {
  int64 city_id = 1;
  int32 x = 2;
  int32 y = 3;
  ExpansionUnlockingType unlocking_type = 4;
  ConstructionDTO construction = 5;
  int32 width = 6;
  int32 height = 7;
  UUID id = 8;
  string expansion_definition_id = 10;
}

message InitialResourceComponentDTO {
}

message InitialGridComponentDTO {
  int32 expansion_size = 1;
}

message GetCityRequest {
  int64 city_id = 1;
  string city_definition_id = 3;
}

message UnlockAreaRequest {
  int64 city_id = 1;
  string expansion_definition_id = 2;
  ExpansionUnlockingType unlocking_type = 3;
  UUID grid_area_id = 5;
}

message FinishUnlockAreaRequest {
  int64 city_id = 1;
  UUID grid_area_id = 2;
}

message SyncUnlockAreaRequest {
  int64 city_id = 1;
  UUID grid_area_id = 2;
}

message SkipUnlockAreaRequest {
  int64 city_id = 1;
  UUID grid_area_id = 2;
}

message PartialPayAreaRequest {
  int64 city_id = 1;
  string expansion_definition_id = 2;
  ExpansionUnlockingType unlocking_type = 3;
  UUID grid_area_id = 5;
  PartialPaymentType invested_premium = 9;
  PartialPaymentType partial_payment_type = 10;
}

message StartCityRequest {
  string definition_id = 1;
}

message BuildingLimitsDTO {
}

message LimitByTypeDTO {
  string type = 1;
  int32 amount = 2;
}

message LimitByGroupDTO {
  string group = 1;
  string resource = 2;
  int32 amount = 3;
}

message ExpansionDefinitionDTO {
  string id = 1;
  string city = 2;
  int32 x = 3;
  int32 y = 4;
  ExpansionType expansion_type = 5;
  ExpansionSubType expansion_sub_type = 6;
  ActionComponentDTO components = 7;
  ActionComponentDTO finish = 8;
}

message ExpansionInfoDTO {
  int32 expansion_size = 1;
}

message ExpansionUnlockingInfoDTO {
  ExpansionUnlockingType unlocking_type = 1;
  int32 available = 2;
  int32 unlocked = 3;
  ExpansionSubType expansion_sub_type = 4;
}

message CityCultureAreaComponentDTO {
  string id = 1;
  int32 x = 2;
  int32 y = 3;
  int32 width = 4;
  int32 height = 5;
  int32 range = 6;
  int32 points = 7;
}

message LinkedExpansionComponentDTO {
  string linked_expansion_definition_id = 1;
}

message CityDeletedPush {
  int64 city_id = 1;
}
