syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "gamedesign_enums.proto";
import "google/protobuf/any.proto";
import "google/protobuf/timestamp.proto";
import "uuid.proto";

message WrappedResponse {
  string error_message = 3;
  string stack_trace = 4;
  SoftErrorType error_type = 5;
  string client_message = 6;
  google.protobuf.Any response = 7;
  PushContextDTO root_context = 8;
}

message WrappedPush {
  PushContextDTO root_context = 1;
}

message PushContextDTO {
  google.protobuf.Any context_info = 1;
}

message RootContextDTO {
}

message VoidResponse {
}

message BatchRequest {
  enum BatchedRequest.Types.RequestMethod {
    POST = 0;
    GET = 1;
  }
  message BatchedRequest {
    UUID uuid = 1;
    string url = 2;
    RequestMethod method = 3;
    google.protobuf.Any request = 4;
    string x_request_id = 5;
    google.protobuf.Timestamp action_at = 6;
  }
}

message BatchResponse {
  message BatchedResponse {
    UUID uuid = 1;
    int32 status_code = 2;
    WrappedResponse response = 3;
  }
}
