syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
import "init.proto";
import "worker.proto";

message ConstructionDTO {
  int64 id = 1;
  string definition_id = 2;
  bool started = 3;
  google.protobuf.Timestamp started_at = 4;
  bool completed = 5;
  google.protobuf.Timestamp complete_at = 6;
  google.protobuf.Duration duration = 7;
}

message ConstructionComponentDTO {
  string id = 1;
  google.protobuf.Duration duration = 3;
  ActionComponentDTO start = 5;
  ActionComponentDTO complete = 6;
  RequiredWorkersDTO workers_required = 8;
  ActionComponentDTO finish = 9;
  bool uses_construction_slots = 10;
}

message RebuildConstructionComponentDTO {
  string id = 1;
  google.protobuf.Duration duration = 3;
  ActionComponentDTO start = 5;
  ActionComponentDTO complete = 6;
  int32 required_workers = 7;
  RequiredWorkersDTO workers_required = 8;
  bool uses_construction_slots = 9;
}

message ConstructionSlotsDefinitionDTO {
  string id = 1;
  int32 default_construction_slots = 2;
  string subscription_benefit = 3;
  int32 subscription_constructon_slots = 4;
}
