syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

message CrmPlaceholderDefinitionDTO {
  string id = 1;
  string external_product_id = 2;
}

message CrmTargetCreatedDTO {
  string target_id = 1;
  bool valid_platforms = 3;
  bool valid_devices = 4;
  bool poll_without_delay = 5;
}

message CrmTargetDeletedPush {
  string target_id = 1;
}

message CrmOfferResurfacingDTO {
  message TriggerDTO {
    float chance_percentage = 1;
    object event = 2;
    object interval = 3;
  }
  message RateLimitDTO {
    int32 amount = 1;
    google.protobuf.Duration interval = 2;
  }
  int64 id = 1;
  google.protobuf.Timestamp created_at = 2;
  google.protobuf.Timestamp expires_at = 3;
  string target_id = 4;
  string content_id = 5;
  int32 content_priority = 6;
}

message CrmOfferResurfacedRequest {
  int64 crm_resurfacing_id = 2;
  string device_size = 3;
  string content_display_point = 4;
}
