syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
import "init.proto";

message DailyRewardDTO {
  DailyRewardDefinitionDTO daily_reward_definition = 1;
  google.protobuf.Timestamp next_collect_after = 2;
  int32 rewards_remaining = 3;
}

message DailyRewardRewardDTO {
  DailyRewardDefinitionDTO daily_reward_definition = 1;
  int32 amount = 2;
}

message DailyRewardDefinitionDTO {
  string definition_id = 1;
  ActionComponentDTO action = 2;
  string reset_cron = 3;
  google.protobuf.Duration duration_between_resets = 4;
  int32 purchase_stack_limit = 5;
}

message DailyRewardCollectRequest {
  string daily_reward_definition_id = 2;
}
