syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "hero_battle.proto";
import "resource.proto";
import "reward.proto";

message EquipmentEquipRequest {
  int64 equipment_id = 1;
  string hero_definition_id = 2;
  PartialPaymentDTO invested_premium = 3;
}

message EquipmentUnequipRequest {
  int64 equipment_id = 1;
  PartialPaymentDTO invested_premium = 2;
}

message EquipmentLevelUpRequest {
  int64 equipment_id = 1;
  PartialPaymentDTO invested_premium = 2;
}

message EquipmentLevelUpResponse {
  bool success = 1;
}

message EquipmentMarkAsSeenRequest {
}

message EquipmentPush {
}

message EquipmentDTO {
  int64 id = 1;
  string equipment_slot_type_definition_id = 2;
  string equipment_set_definition_id = 3;
  string equipment_rarity_definition_id = 4;
  int32 level = 5;
  string equipped_on_hero_definition_id = 6;
  bool is_new = 7;
  EquipmentMainAttributeDTO main_attribute = 8;
}

message AllEquipmentUnitDataDTO {
}

message EquipmentUnitDataDTO {
  string equipment_slot_type_definition_id = 1;
  string equipment_set_definition_id = 2;
  string equipment_rarity_definition_id = 3;
  int32 level = 4;
  EquipmentMainAttributeDTO main_attribute = 5;
}

message EquipmentMainAttributeDTO {
  string unit_stat_attribute_definition_id = 1;
  UnitStatBoostDTO stat_boost = 2;
}

message EquipmentSubAttributeDTO {
  string unit_stat_attribute_definition_id = 1;
  UnitStatBoostDTO stat_boost = 2;
  int32 unlocked_at_level = 3;
  bool unlocked = 4;
  float rolled_value = 5;
}

message EquipmentRarityDefinitionDTO {
  string definition_id = 1;
}

message EquipmentSlotTypeDefinitionDTO {
  string definition_id = 1;
  string equipment_slot_group_definition_id = 2;
  int32 order = 3;
}

message EquipmentSlotGroupDefinitionDTO {
  string definition_id = 1;
}

message EquipmentSetDefinitionDTO {
  string definition_id = 1;
  string equipment_slot_group_definition_id = 2;
  int32 set_bonus_boosts = 3;
  int32 tier = 4;
}

message EquipmentConstantsDefinitionDTO {
  string definition_id = 1;
}

message EquipmentProgressionDTO {
  string equipment_progression_setup_definition_id = 1;
  string equipment_progression_cost_definition_id = 2;
  string equipment_main_attribute_value_definition_id = 3;
}

message EquipmentProgressionSetupDefinitionDTO {
  string definition_id = 1;
  int32 max_level = 2;
}

message EquipmentProgressionCostDefinitionDTO {
  string definition_id = 1;
}

message EquipmentLevelCostDataDTO {
  string costs = 1;
  string equipment_level_up_chance_definition_id = 2;
}

message EquipmentMainAttributeValueDefinitionDTO {
  string definition_id = 1;
}

message EquipmentMainAttributeValueProgressionDTO {
}

message EquipmentRarityPoolDefinitionDTO {
  string definition_id = 1;
}

message EquipmentSetPoolDefinitionDTO {
  string definition_id = 1;
}

message EquipmentSlotPoolDefinitionDTO {
  string definition_id = 1;
}

message EquipmentRewardDTO {
  BaseRewardDTO base_data = 1;
  string rarity_definition_pool_id = 2;
  string set_definition_pool_id = 3;
  string slot_type_definition_pool_id = 4;
  int32 amount = 5;
  string asset_id = 6;
}

message EquipmentGrantedRewardDTO {
  EquipmentRewardDTO origin = 1;
}

message EquipmentCapRequirementDTO {
  string id = 1;
  int32 max_equipment_owned = 2;
}

message EquipmentSellRequest {
  PartialPaymentDTO equipment_ids = 1;
  PartialPaymentDTO invested_premium = 2;
}

message EquipmentRemovedPush {
}

message EquipmentSaleDefinitionDTO {
  string id = 1;
}

message EquipmentUnequipDefinitionDTO {
  string id = 1;
}

message HaveEquipmentTaskDTO {
  string id = 1;
  int64 amount = 2;
  int32 min_level = 3;
}

message EquipHeroTaskDTO {
  string id = 1;
  int64 amount = 2;
}

message LevelUpEquipmentTaskDTO {
  string id = 1;
  int64 amount = 2;
  int32 level = 3;
  bool count_higher_levels = 4;
}

message ObtainEquipmentTaskDTO {
  string id = 1;
  int64 amount = 2;
  string rarity_definition_id = 3;
}
