syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "init.proto";
import "player.proto";

enum FriendReferralBonusFor {
  FriendReferralBonusFor_REFERRAL_SENT = 0;
  FriendReferralBonusFor_REFERRAL_RECEIVED = 1;
}

message FriendReferralDefinitionDTO {
  string id = 1;
  ActionComponentDTO referral_bonus = 2;
}

message FriendReferralBonusReceivedDTO {
  PlayerInfoDTO other_player = 1;
  FriendReferralBonusFor bonus_for = 2;
}

message FriendReferralMilestoneProgressDTO {
  int32 successful_invitations = 1;
  int32 last_claimed_milestone = 2;
}
