syntax = "proto3";

package InnoGames.Generated.Protobuf;

enum CastEffectMovementPattern {
  PROTO_DEFAULT_CASTEFFECTMOVEMENTPATTERN = 0;
  Line = 2368532;
  None = 2433880;
  Spiral = 1812072687;
  Triangle = 1562406440;
}

enum InventoryDisplayType {
  PROTO_DEFAULT_INVENTORYDISPLAYTYPE = 0;
  ANTIMATTER = 433472349;
  FRAGMENT = 867642800;
}

enum FeatureFlags {
  PROTO_DEFAULT_FEATUREFLAGS = 0;
  ATHShop = 32115467;
  AbortableRequestQueue = 1177207476;
  ActionTimeValidation = 1424196380;
  AllianceBroadcastPushNotifications = 1447544092;
  AllianceCity = 1770141282;
  AllianceCityIntroductionVideo = 898311743;
  AnubisTrailer = 202478159;
  AvA = 66188;
  BACKENDTRANSLATIONS = 960442282;
  BattleValidation = 285356913;
  BattleValidationThrowException = 508407334;
  BrowserFriendReferral = 890630781;
  COLLECTORMIGRATION = 1942950369;
  CRMPUSH = 1754373592;
  ChangeEmail = 10830420;
  CompressedSocketPush = 171549778;
  CrmPromoCodeApi = 256831932;
  DailyBonus = 801303130;
  DailyOffers = 1293020400;
  DisableEventVfx = 862025142;
  DisableQualitySettings = 1614903718;
  DtcAndroidDefaultOff = 774581706;
  DtcAndroidDefaultOn = 717723172;
  EVENTVFX = 1060767470;
  EliteArena = 1468310444;
  EquipmentMode2 = 1090992673;
  EquipmentMode3 = 1090992674;
  EventRanking = 2050688092;
  ExtendedEventDismissalLog = 1273996752;
  FriendReferral = 1708640133;
  GarbageCollectHandlerEnabled = 1141350580;
  HideDirectChat = 1646337565;
  InAppBrowserPayment = 1202389882;
  JoystickBattleTutorial = 1446367410;
  LateGothicEra = 1798178264;
  LoginHubAccountSettings = 1778842908;
  LoginHubOnBrowser = 1830147907;
  MaliEmpire2023 = 2044063068;
  MergeEventRequestBatch = 2099698579;
  Offerwall = 345424378;
  PantheonReset = 112034140;
  REGISTERACCOUNT = 1870738934;
  REMOVEUSERNAME = 189440346;
  RevenueUsedPercentage = 1879838381;
  ShowBrowserGuestRegistration = 1233101658;
  SkipBattle = 1655481143;
  StarUp = 1808617299;
  StaticPlayerSeed = 841663008;
  TimelineGrowthFund = 1919028333;
  V1_45 = 80975525;
  VideoAdsExcludeDevices = 256095400;
  VideoAdsExcludeDevicesByMemory = 892424272;
  VoucherEntry = 105457020;
  WebSocketReconnectInstantWakeup = 1862064912;
  WorldFair = 1168609866;
  WorldSelection = 392092102;
  hideSeason21Heroes = 789508876;
  hideSeason22Heroes = 1677012557;
  hideSeason23Heroes = 1730451058;
  legendary_promotion = 1068910751;
}

enum SoftErrorType {
  SoftErrorType_NONE = 0;
  SoftErrorType_ALLIANCE_ALLIANCE_HAS_TOO_MANY_PENDING_INVITES = 53545465;
  SoftErrorType_ALLIANCE_APPLICATION_COOLDOWN = 380839205;
  SoftErrorType_ALLIANCE_APPLICATION_EXISTS = 1418795060;
  SoftErrorType_ALLIANCE_APPLICATION_NOT_FOUND = 934893210;
  SoftErrorType_ALLIANCE_APPLICATION_STATE_INVALID = 997044889;
  SoftErrorType_ALLIANCE_BROADCAST_COOLDOWN = 1675536074;
  SoftErrorType_ALLIANCE_CITY_AC_PREMIUM_SLOT_NOT_AVAILABLE = 1583159154;
  SoftErrorType_ALLIANCE_CITY_CRATE_ALREADY_PAID = 1876303874;
  SoftErrorType_ALLIANCE_CITY_CRATE_NOT_FOUND = 663929945;
  SoftErrorType_ALLIANCE_CITY_INCIDENT_ALREADY_STARTED = 1393630688;
  SoftErrorType_ALLIANCE_CITY_INCIDENT_MAX_REWARD_UNLOCKED = 1711227714;
  SoftErrorType_ALLIANCE_CITY_INCIDENT_NOT_FINISHED = 2043345032;
  SoftErrorType_ALLIANCE_CITY_INCIDENT_NOT_FOUND = 1124210204;
  SoftErrorType_ALLIANCE_CITY_INCIDENT_NOT_VALID_YET = 619423329;
  SoftErrorType_ALLIANCE_CITY_INCIDENT_NO_LONGER_VALID = 908034870;
  SoftErrorType_ALLIANCE_CITY_PROCESS_ALREADY_FINISHED = 1322653508;
  SoftErrorType_ALLIANCE_CITY_PROCESS_PREMIUM_MISMATCH = 1931744519;
  SoftErrorType_ALLIANCE_CITY_PROCESS_SLOT_IN_USE = 548641451;
  SoftErrorType_ALLIANCE_CITY_PROCESS_SLOT_NOT_ACTIVE = 401000848;
  SoftErrorType_ALLIANCE_CITY_PROCESS_SLOT_NOT_UNLOCKED = 1664701491;
  SoftErrorType_ALLIANCE_CITY_QUARTER_NOT_UPGRADING = 773149031;
  SoftErrorType_ALLIANCE_CITY_QUARTER_UPGRADING = 1024907507;
  SoftErrorType_ALLIANCE_CITY_TECHNOLOGY_ALREADY_UNLOCKED = 798595894;
  SoftErrorType_ALLIANCE_CITY_WRONG_ALLIANCE = 324844188;
  SoftErrorType_ALLIANCE_CLOSED = 269590637;
  SoftErrorType_ALLIANCE_INVALID_APPLICATION = 1047705241;
  SoftErrorType_ALLIANCE_INVALID_CHARACTER_IN_NAME = 1367812826;
  SoftErrorType_ALLIANCE_MAX_PENDING_REACHED = 1947366386;
  SoftErrorType_ALLIANCE_MAX_PENDING_REACHED_BY_PLAYER = 1436544808;
  SoftErrorType_ALLIANCE_MAX_SIZE_REACHED = 2052193232;
  SoftErrorType_ALLIANCE_MEMBER_NOT_FOUND = 216948018;
  SoftErrorType_ALLIANCE_NAME_ALREADY_EXISTS = 237374742;
  SoftErrorType_ALLIANCE_NAME_DOUBLE_WHITESPACE = 1940546552;
  SoftErrorType_ALLIANCE_NOT_FOUND = 1495406539;
  SoftErrorType_ALLIANCE_NOT_OPEN = 1891692311;
  SoftErrorType_ALLIANCE_PLAYER_ALLIANCES_NOT_UNLOCKED = 1776407119;
  SoftErrorType_ALLIANCE_PLAYER_ALREADY_MEMBER = 8559490;
  SoftErrorType_ALLIANCE_PLAYER_DOESNT_ACCEPT_INVITES = 177541590;
  SoftErrorType_ALLIANCE_PLAYER_HAS_TOO_MANY_PENDING_INVITES = 1977051313;
  SoftErrorType_ALLIANCE_PLAYER_INVITE_DUPLICATE = 659633166;
  SoftErrorType_ALLIANCE_PLAYER_SELF_KICK = 68269372;
  SoftErrorType_ALLIANCE_REJOIN_TIMEOUT = 1764746528;
  SoftErrorType_ALLIANCE_ROLE_UNCHANGED = 956725421;
  SoftErrorType_BATTLE_BATTLE_NOT_ACTIVE = 604636761;
  SoftErrorType_BATTLE_INVALID_LOCATION = 1777525437;
  SoftErrorType_CHEAT_EXECUTION_FAILED = 42817879;
  SoftErrorType_CRM_ALREADY_REDEEMED = 423086742;
  SoftErrorType_CRM_EXPIRED = 1749223421;
  SoftErrorType_CRM_NOT_FOUND = 341994034;
  SoftErrorType_CRM_PLATFORM_MISMATCH = 1783157998;
  SoftErrorType_CRM_RATE_LIMIT_REACHED = 1697841015;
  SoftErrorType_CRM_REDEMPTIONS_EXCEEDED = 587260878;
  SoftErrorType_CRM_SERVICE_UNAVAILABLE = 1548617342;
  SoftErrorType_CRM_UNEXPECTED_ERROR = 752167294;
  SoftErrorType_EVENT_EVENT_NOT_ACTIVE = 1207491587;
  SoftErrorType_EVENT_EVENT_RANKING_NOT_FOUND = 584256804;
  SoftErrorType_FEATURE_FLAG_FEATURE_DISABLED = 982993976;
  SoftErrorType_GENERAL_UNKNOWN = 52884052;
  SoftErrorType_HERO_TREASURE_HUNT_ALLIANCE_MISMATCH = 1668405732;
  SoftErrorType_HERO_TREASURE_HUNT_NOT_IN_ALLIANCE = 1702619467;
  SoftErrorType_ONE_ON_ONE_CHAT_CANNOT_CHAT_WITH_SELF = 590978444;
  SoftErrorType_ONE_ON_ONE_CHAT_PLAYER_DOES_NOT_ALLOW_CHAT = 523383632;
  SoftErrorType_ONE_ON_ONE_CHAT_TARGET_PLAYER_FEATURE_NOT_UNLOCKED = 757326870;
  SoftErrorType_PLAYER_PROFILE_PLAYER_PROFILE_NOT_FOUND = 1739575217;
  SoftErrorType_PVP_EVENT_NOT_ENDED = 1224076493;
  SoftErrorType_PVP_MUST_COMPLETE_ACTIVE_BATTLE = 1397613253;
  SoftErrorType_PVP_NO_ACTIVE_BATTLE = 1721238607;
  SoftErrorType_PVP_REVENGE_LOCATION_NOT_FOUND = 1487949283;
  SoftErrorType_REQUEST_CLIENT_OUT_OF_DATE = 1619735240;
  SoftErrorType_REQUEST_CONCURRENCY_TIMEOUT = 1890651362;
  SoftErrorType_REQUEST_SERVER_UPDATED = 657935190;
  SoftErrorType_REQUEST_SESSION_EXPIRED = 555876709;
  SoftErrorType_RESOURCE_PREMIUM_SPEND_MISMATCH = 598869503;
  SoftErrorType_SEASON_PASS_NOT_ACTIVE = 404846197;
  SoftErrorType_VOUCHER_NOT_FOUND = 55976478;
  SoftErrorType_WONDER_CONTRIBUTION_ALREADY_CREATED = 1103876367;
  SoftErrorType_WONDER_CONTRIBUTION_NOT_OPEN = 1636024120;
  SoftErrorType_WONDER_MAX_CONTRIBUTIONS_REACHED = 15911454;
  SoftErrorType_WONDER_MAX_LEVEL_REACHED = 605409729;
  SoftErrorType_WONDER_NOT_IN_SAME_ALLIANCE = 186937567;
  SoftErrorType_WO_A_CANNOT_HEAL_NON_GARRISONED_ALLY_HERO = 1177858223;
  SoftErrorType_WO_A_CANNOT_HEAL_OUTSIDE_ALLIANCE = 596455382;
  SoftErrorType_WO_A_EVENT_NOT_ACTIVE = 394574133;
  SoftErrorType_WO_A_HEALING_ITEM_KNOCKED_OUT_MISMATCH = 1299559884;
  SoftErrorType_WO_A_HEROES_MUST_BE_IN_SAME_SLOT = 679692956;
  SoftErrorType_WO_A_HERO_ALREADY_AT_FULL_HEALTH = 726895154;
  SoftErrorType_WO_A_MAX_ATTACKING_ALLIANCES = 1434618878;
  SoftErrorType_WO_A_MAX_REPAIRING_PLAYERS_REACHED = 1605701026;
  SoftErrorType_WO_A_NOT_IN_ALLIANCE = 1442875015;
  SoftErrorType_WO_A_NOT_IN_CONFLICT_PHASE = 2019278078;
  SoftErrorType_WO_A_NOT_IN_DIVISION = 651005;
  SoftErrorType_WO_A_OUT_OF_SYNC = 2079162612;
  SoftErrorType_WO_A_POI_NOT_CONTROLLED = 1757508595;
  SoftErrorType_WO_A_POI_NOT_UNLOCKED = 729574178;
  SoftErrorType_WO_A_POI_OWNED_BY_ALLIANCE = 688963566;
  SoftErrorType_WO_A_POI_UNDER_SHIELD = 803128573;
  SoftErrorType_WO_A_SLOT_NOT_AVAILABLE = 1013844902;
}
