syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/any.proto";
import "google/protobuf/duration.proto";
import "hero_abilities.proto";
import "hero_battle.proto";

message RecordedBattleDTO {
  BattleConfigDTO config = 1;
  int64 actions = 2;
  int64 last_update_time_old = 3;
  FixedPointDTO debug_events = 4;
  FixedPointDTO last_update_time = 5;
}

message BattleConfigDTO {
  message VfxHitTime {
    string vfx_type = 1;
    float hit_time_old = 2;
    FixedPointDTO hit_time = 3;
  }
  message Constants {
    AttackCalculationValuesDTO attack_calculation_values = 1;
    bool use_bidirectional_color_factor = 2;
    float splash_damage_exponent_old = 3;
    FixedPointDTO status_effect_interactions = 4;
    FixedPointDTO splash_damage_exponent = 5;
  }
  message SquadSpawnData {
    int32 spawn_point_id = 1;
    UnitSpawnDataDTO hero = 2;
    UnitSpawnDataDTO support = 3;
  }
  message WaveConfig {
  }
  uint32 random_seed = 1;
  google.protobuf.Duration duration = 2;
  bool waves = 6;
  bool pause_for_enemy_abilities = 7;
  bool wait_for_active_abilities_on_battle_end = 8;
  bool allow_player_input = 9;
  Constants constants = 11;
  google.protobuf.Any extra_abilities = 26;
  google.protobuf.Any result_calculation = 27;
}

message BattleValidationRequestDTO {
  RecordedBattleDTO recorded_battle = 1;
}

message BattleValidationResponseDTO {
  BattleResultDTO result = 1;
}

message BattleResultDTO {
  bool is_win = 1;
  HeroBattleLostReason lose_reason = 2;
  int32 win_stars = 3;
}

message BattleResultUnitStats {
  string definition_id = 1;
  int32 tracked_stats = 3;
  int32 battle_unit_id = 4;
}
