syntax = "proto3";

package InnoGames.Generated.Protobuf;

enum BattleEffectType {
  BattleEffectType_AURA = 0;
  BattleEffectType_BUFF = 1;
  BattleEffectType_STATUS = 2;
}

enum BattleEffectOrientation {
  BattleEffectOrientation_POSITIVE = 0;
  BattleEffectOrientation_NEGATIVE = 1;
}

enum BattleEffectOrigin {
  BattleEffectOrigin_Unspecified = 0;
  BattleEffectOrigin_HeroAbility = 1;
  BattleEffectOrigin_RelicAbility = 2;
  BattleEffectOrigin_StatusEffectInteraction = 3;
  BattleEffectOrigin_StatChangeTrigger = 4;
  BattleEffectOrigin_BasicAttack = 5;
  BattleEffectOrigin_StatusEffectTrigger = 6;
}

enum StatChangeTriggerUnitOrigin {
  StatChangeTriggerUnitOrigin_Any = 0;
  StatChangeTriggerUnitOrigin_Self = 1;
  StatChangeTriggerUnitOrigin_Friend = 2;
  StatChangeTriggerUnitOrigin_Enemy = 3;
  StatChangeTriggerUnitOrigin_AnyButSelf = 4;
}

enum BattleEffectParentCompletionBehaviour {
  BattleEffectParentCompletionBehaviour_CONTINUE = 0;
  BattleEffectParentCompletionBehaviour_COMPLETE = 1;
  BattleEffectParentCompletionBehaviour_COMPLETE_AND_OVERWRITE_EXECUTION_TIME = 2;
}

enum AbilityClassificationType {
  AbilityClassificationType_NONE = 0;
  AbilityClassificationType_SINGLE_TARGET_HEAL = 1;
  AbilityClassificationType_MULTI_TARGET_HEAL = 2;
  AbilityClassificationType_SELF_TARGET_HEAL = 3;
  AbilityClassificationType_MULTI_STRIKER = 4;
}
