syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "gamedesign_enums.proto";
import "google/protobuf/any.proto";
import "google/protobuf/duration.proto";
import "hero_abilities_enums.proto";
import "hero_battle.proto";

message BattleAbilityDefinitionDTO {
  string id = 1;
  google.protobuf.Any trigger = 2;
  google.protobuf.Duration effects = 3;
  google.protobuf.Duration duration = 4;
  string description_loca_key = 5;
  google.protobuf.Duration description_parameters = 6;
  google.protobuf.Duration wind_up_duration = 7;
  BattleAbilityExecutionRequirementDTO execution_requirement = 8;
  int32 animation_index = 9;
  int32 status_effects = 10;
  int32 total_spawned_units = 11;
  bool classifications = 13;
  bool display_as_passive = 14;
  string name_loca_key = 15;
}

message BattleAbilityDescriptionParameterDTO {
  double value = 1;
  string type = 2;
}

message BattleEffectsDTO {
  google.protobuf.Duration at_time = 1;
}

message BattleEffectTargetedDTO {
  google.protobuf.Any target = 1;
  google.protobuf.Any effect = 2;
  int32 distribute_instances = 3;
}

message BattleAbilityExecutionRequirementDTO {
  google.protobuf.Any target = 1;
  int32 min_units = 2;
}

message BattleStatusEffectDTO {
  message StackStrategyDTO {
    string battle_status_effect_id = 1;
    string stack_strategy = 2;
  }
  string id = 1;
  BattleEffectOrientation orientation = 2;
  BattleEffectType type = 4;
  google.protobuf.Any stack_strategies = 5;
  google.protobuf.Any duration_adjuster = 6;
  int32 stack_limit = 7;
}

message BattleEffectModifierTypeDTO {
  string id = 1;
}

message BattleStatusEffectInteractionDTO {
  string id = 1;
  google.protobuf.Any condition = 2;
}

message BattleVfxTypeDTO {
  string id = 1;
  float hit_time = 2;
}

message ManualTriggerDTO {
  float special_consumed = 2;
  bool allow_manual_completion = 3;
}

message ConditionalTriggerDTO {
  google.protobuf.Any ready = 2;
  google.protobuf.Any trigger = 3;
  ConditionalTriggerReadyVfxConfigDTO ready_vfx = 4;
}

message ConditionalTriggerReadyVfxConfigDTO {
  string vfx_type = 1;
  google.protobuf.Any affected_units_filter = 2;
}

message OrConditionDTO {
}

message AndConditionDTO {
}

message AbilityCompletedConditionDTO {
  string ability_definition_id = 1;
  google.protobuf.Any origin_unit_filter = 2;
}

message AbilityTriggeredConditionDTO {
  string ability_definition_id = 1;
  google.protobuf.Any origin_unit_filter = 3;
}

message ActiveAbilityTriggerRequestedConditionDTO {
  google.protobuf.Any origin_unit_filter = 1;
}

message BattleStartConditionDTO {
}

message WaveStartConditionDTO {
}

message ActiveByDefaultConditionDTO {
}

message AlwaysActiveConditionDTO {
}

message CountdownConditionDTO {
  google.protobuf.Duration duration = 1;
}

message UnitCountConditionDTO {
  google.protobuf.Any filter = 1;
  int32 min_units = 2;
  int32 max_units = 3;
  bool ignore_lanes = 4;
}

message DamageDealtConditionDTO {
  bool require_critical_hit = 1;
  BattleEffectOrigin effect_origin = 2;
}

message UnitDefinitionIdsConditionDTO {
}

message UnitDefeatedConditionDTO {
  google.protobuf.Any defeated_unit_filter = 1;
  google.protobuf.Any defeated_by_filter = 2;
}

message UnitAffectedByMoveToEffectConditionDTO {
  StatChangeTriggerUnitOrigin unit_origin = 1;
}

message HasStatusEffectConditionDTO {
  string status_effect_definition_id = 1;
  bool invert = 2;
}

message UnitStatConditionDTO {
  string stat_id = 1;
  float min_percentage = 2;
  float max_percentage = 3;
  string base_stat_id = 4;
}

message BattleAbilityTargetSelectDTO {
  google.protobuf.Any filter = 1;
  google.protobuf.Any sort = 2;
  float radius = 3;
  int32 max_units = 4;
  int32 skip_units = 5;
  bool append_skipped_units = 6;
}

message BattleAbilityLocationPointDTO {
  int32 x = 1;
  int32 y = 2;
}

message AllUnitsTargetDTO {
  BattleAbilityTargetSelectDTO select = 1;
}

message SelfTargetDTO {
  BattleAbilityTargetSelectDTO select = 1;
}

message PreviousTargetCenterTargetDTO {
  BattleAbilityTargetSelectDTO select = 1;
}

message PreviousTargetUnitsTargetDTO {
  BattleAbilityTargetSelectDTO select = 1;
}

message SpawnPointTargetDTO {
  BattleAbilityTargetSelectDTO select = 1;
}

message AbilityTriggeredPointTargetDTO {
  BattleAbilityTargetSelectDTO select = 1;
}

message TargetedUnitTargetDTO {
  BattleAbilityTargetSelectDTO select = 1;
}

message DamagedUnitTargetDTO {
  BattleAbilityTargetSelectDTO select = 1;
  bool require_critical_hit = 2;
}

message AffectedUnitTargetDTO {
  BattleAbilityTargetSelectDTO select = 1;
}

message DefeatedUnitTargetDTO {
  BattleAbilityTargetSelectDTO select = 1;
}

message RandomTargetDTO {
  BattleAbilityTargetSelectDTO select = 1;
}

message MaxUnitCoveredTargetDTO {
  BattleAbilityTargetSelectDTO select = 1;
  bool offset_by_target_unit_radius = 2;
}

message BattlefieldSlotTargetDTO {
  BattleAbilityTargetSelectDTO select = 1;
}

message BattlefieldLocationPointTargetDTO {
  BattleAbilityTargetSelectDTO select = 1;
  google.protobuf.Any selection_strategy = 2;
}

message FurthestPointSelectionDTO {
  float heroes_score_multiplier = 1;
  float non_heroes_score_multiplier = 2;
}

message BattlefieldCenterPointSelectionDTO {
}

message MaxUnitsCoveredPointSelectionDTO {
  bool offset_by_target_unit_radius = 1;
}

message EnemyUnitsFilterDTO {
}

message FriendlyUnitsFilterDTO {
}

message IsHeroUnitFilterDTO {
}

message IsNoHeroUnitFilterDTO {
}

message ExcludeAffectedTargetFilterDTO {
}

message ImmunitiesFilterDTO {
  bool include = 1;
}

message AndFilterDTO {
}

message StatusEffectFilterDTO {
  string with_status_effect_definition_id = 1;
}

message UnitTypeFilterDTO {
  string unit_type_definition_id = 1;
  bool include = 2;
}

message SelfFilterDTO {
}

message ByUnitStatSortDTO {
  string stat_id = 1;
}

message ByUnitStatDiffSortDTO {
  string minuend_stat_id = 1;
  string subtrahend_stat_id = 2;
}

message ReversedSortDTO {
  google.protobuf.Any sort = 1;
}

message ByDistanceToCenterSortDTO {
}

message ByCombatPowerSortDTO {
}

message RandomSortDTO {
}

message HeroesFirstSortDTO {
  google.protobuf.Any sort = 1;
}

message WithoutStatusEffectFirstSortDTO {
  google.protobuf.Any sort = 1;
  string status_effect_definition_id = 2;
}

message BaseBattleEffectDTO {
}

message StatChangeEffectDTO {
  string stat_id = 1;
  float absolute_change = 2;
  string base_stat_id = 3;
  float percentage_of_base_stat = 4;
  bool use_target_stat = 5;
  bool vfx_types = 6;
  bool use_stat_at_battle_start = 7;
  string modifier_type_id = 9;
  google.protobuf.Any stat_target = 10;
  float stat_change_excess_value = 11;
  float stat_change_trigger_modifier_value = 12;
  float missing_hit_points_value = 13;
  google.protobuf.Any value_source = 14;
  float min_cap_value = 15;
  float max_cap_value = 16;
}

message UnitCountStatChangeEffectDTO {
  StatChangeEffectDTO stat_change = 1;
  google.protobuf.Any unit_count = 2;
}

message InvincibilityEffectDTO {
}

message RecurringEffectDTO {
  google.protobuf.Duration effects = 1;
  google.protobuf.Duration duration = 2;
  int32 ticks = 3;
  string vfx_types = 4;
  string status_effect_definition_id = 5;
  BattleEffectParentCompletionBehaviour parent_completion_behaviour = 6;
}

message TemporaryEffectDTO {
  google.protobuf.Duration effects = 1;
  google.protobuf.Duration duration = 2;
  string vfx_types = 4;
  string status_effect_definition_id = 5;
  string modifier_type_id = 6;
  BattleEffectParentCompletionBehaviour parent_completion_behaviour = 7;
}

message TransformUnitEffectDTO {
  google.protobuf.Duration effects = 1;
  google.protobuf.Duration duration = 2;
  string vfx_types = 3;
  string status_effect_definition_id = 4;
  BattleEffectParentCompletionBehaviour parent_completion_behaviour = 5;
  string asset_id = 6;
}

message ChanceEffectDTO {
  google.protobuf.Any effect = 1;
  float chance = 2;
}

message CleanseEffectDTO {
  BattleEffectOrientation effect_types = 3;
  BattleEffectOrientation orientation = 4;
  int32 max_count = 5;
}

message ImmunityEffectDTO {
  BattleEffectOrientation effect_types = 3;
  BattleEffectOrientation orientation = 4;
}

message MoveToEffectDTO {
  google.protobuf.Any vfx_types = 1;
  google.protobuf.Any destination = 3;
  Vector2DTO destination_offset = 4;
  float unit_radius_multiplier = 5;
}

message Vector2DTO {
  float x = 1;
  float y = 2;
}

message StunEffectDTO {
  google.protobuf.Any vfx_types = 1;
  google.protobuf.Any destination = 2;
}

message CharmEffectDTO {
  BattleEffectOrientation vfx_types = 1;
  BattleEffectOrientation orientation = 2;
  float distance = 3;
}

message DamageBonusChargeEffectDTO {
  google.protobuf.Any vfx_types = 1;
  google.protobuf.Any value_source = 2;
}

message FreezeEffectDTO {
}

message TauntEffectDTO {
  google.protobuf.Any vfx_types = 1;
  google.protobuf.Any target = 2;
}

message MindControlEffectDTO {
}

message CastEffectDTO {
  string vfx_types = 1;
  string effects = 2;
  string asset_id = 3;
  CastEffectMovementPattern movement_pattern = 4;
  float movement_pattern_scale = 5;
  google.protobuf.Any filter = 6;
  float radius = 7;
  int32 ticks = 8;
  google.protobuf.Duration duration = 9;
  bool hit_once_per_target = 10;
}

message AuraEffectDTO {
  google.protobuf.Duration effects = 1;
  google.protobuf.Duration duration = 2;
  int32 ticks = 3;
  string vfx_types = 4;
  string status_effect_definition_id = 5;
  float radius = 6;
  google.protobuf.Any filter = 7;
  BattleEffectParentCompletionBehaviour parent_completion_behaviour = 8;
}

message SpiritLinkEffectDTO {
  float vfx_types = 1;
  float damage_percent = 2;
}

message DespawnEffectDTO {
}

message DamageTransferEffectDTO {
  float vfx_types = 1;
  float damage_percent = 2;
  BattleEffectOrientation orientation = 3;
  BattleEffectOrigin effect_origin = 4;
}

message AbilityBlockEffectDTO {
}

message NonTargetableEffectDTO {
  enum ModeDTO {
    ALL = 0;
    FRIENDLY = 1;
    ENEMY = 2;
  }
  ModeDTO vfx_types = 1;
  ModeDTO mode = 2;
}

message GhostingEffectDTO {
}

message MultiLaneTargetableEffectDTO {
}

message SpawnSquadEffectDTO {
  message SquadSpawnData {
    UnitSpawnDataDTO hero = 1;
    UnitSpawnDataDTO support_unit = 2;
  }
  HeroUnitDTO vfx_types = 1;
  HeroUnitDTO hero_unit = 2;
  HeroUnitDTO supporting_unit = 3;
  bool stat_transfer_mappings = 4;
  bool inherit_caster_level = 5;
  BattleAbilityLocationPointDTO spawn_offset = 6;
  bool inherit_power_value = 7;
  SquadSpawnData spawn_data = 8;
}

message UnitSpawnDataDTO {
  message AbilityCreateInfo {
    BattleAbilityDefinitionDTO definition = 1;
    bool is_relic_ability = 2;
  }
  string definition_id = 1;
  string color_definition_id = 2;
  string type_definition_id = 3;
  float power = 4;
  bool abilities = 7;
  bool repeat_last_ability = 8;
  int32 units_per_row = 9;
}

message StatTransferMappingDTO {
  string source_stat_id = 1;
  string target_stat_id = 2;
  float transfer_percentage = 3;
  bool use_base_stat = 4;
}

message PropagateStatusEffectDTO {
  string vfx_types = 1;
  string status_effect_definition_id = 2;
  bool propagate_whole_stack = 3;
}

message AddPassiveAbilityEffectDTO {
  string vfx_types = 1;
  string ability_definition_id = 2;
}

message ReplaceActiveAbilitySequenceEffectDTO {
  bool ability_definition_ids = 2;
  bool repeat_last_ability = 3;
}

message CreateStatChangeTriggerEffectDTO {
  CreateStatChangeTriggerEffectConditionDTO vfx_types = 1;
  CreateStatChangeTriggerEffectConditionDTO condition = 2;
  float change_modifier = 3;
  bool effects = 4;
  bool use_origin_as_target_position = 5;
}

message CreateStatChangeTriggerEffectConditionDTO {
  string stat_id = 1;
  BattleEffectOrientation orientation = 2;
  StatChangeTriggerUnitOrigin unit_origin = 3;
  BattleEffectOrigin effect_origin = 4;
  google.protobuf.Any filter = 5;
  bool requires_excess_value = 6;
}

message CreateStatusEffectTriggerEffectDTO {
  StatusEffectTriggerConditionDTO vfx_types = 1;
  StatusEffectTriggerConditionDTO condition = 2;
}

message StatusEffectTriggerConditionDTO {
  string status_effect_group = 1;
  StatChangeTriggerUnitOrigin unit_origin = 2;
  BattleEffectOrigin effect_origin = 3;
}

message DamageEffectDTO {
  float vfx_types = 1;
  float damage = 2;
  bool apply_evasion = 3;
  bool apply_accuracy = 4;
  bool piercing_damage = 5;
  bool calculate_damage = 6;
  string modifier_type_id = 7;
}

message StatPercentageDTO {
  string base_stat_id = 1;
  bool use_target_stat = 2;
  google.protobuf.Any stat_target = 3;
  bool use_stat_at_battle_start = 4;
  float multiplier = 5;
}

message ChargeTimeStatPercentageDTO {
  string ability = 1;
  float min_percentage = 2;
  float max_percentage = 3;
  BattleEffectOrientation change_orientation = 4;
  string base_stat_id = 5;
  bool use_target_stat = 6;
  bool use_stat_at_battle_start = 7;
  google.protobuf.Any stat_target = 8;
}

message StatusEffectStackMultiplierDTO {
  google.protobuf.Any value_source = 1;
  string status_effect_definition_id = 2;
  float multiplier = 3;
}

message StatChangeExcessValueDTO {
  float multiplier = 1;
}

message EffectDurationDTO {
  float multiplier = 1;
}

message PowerLevelPenaltyAdjusterDTO {
  string id = 1;
  float accepted_diff_percentage = 2;
  float accepted_diff_flat = 3;
  float penalty = 4;
  float min_cap_percentage = 5;
}
