syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/any.proto";
import "google/protobuf/duration.proto";
import "hero_battle_log.proto";
import "hero_shared.proto";
import "uuid.proto";

enum HeroBattleState {
  HeroBattleState_ACTIVE = 0;
  HeroBattleState_WON = 1;
  HeroBattleState_LOST = 2;
}

enum HeroBattleLostReason {
  HeroBattleLostReason_DEFEATED = 0;
  HeroBattleLostReason_TIME_IS_UP = 1;
  HeroBattleLostReason_RETREATED = 2;
}

enum HeroBattleUnitStyle {
  HeroBattleUnitStyle_DEFAULT = 0;
  HeroBattleUnitStyle_MUMMY = 1;
}

enum UnitStatBoostSourceDTO {
  UNIT_STAT_BOOST_SOURCE_UNKNOWN = 0;
  UNIT_STAT_BOOST_SOURCE_UNIT = 1;
  UNIT_STAT_BOOST_SOURCE_AWAKENING = 2;
  UNIT_STAT_BOOST_SOURCE_BARRACKS = 3;
  UNIT_STAT_BOOST_SOURCE_RELICS = 4;
  UNIT_STAT_BOOST_SOURCE_EQUIPMENT_SET = 5;
  UNIT_STAT_BOOST_SOURCE_EQUIPMENT_MAIN_ATTRIBUTE = 6;
  UNIT_STAT_BOOST_SOURCE_EQUIPMENT_SUB_ATTRIBUTE = 7;
  UNIT_STAT_BOOST_SOURCE_BATTLE_MODE = 8;
  UNIT_STAT_BOOST_SOURCE_PANTHEON = 9;
  UNIT_STAT_BOOST_SOURCE_UNIT_DEFINITION = 10;
}

message HeroBattleResult {
  HeroBattleState state = 1;
  HeroBattleLostReason lost_reason = 2;
  int32 stars = 3;
}

message HeroBattlePush {
  HeroBattleDataDTO battle = 1;
}

message HeroStartBattleRequest {
  UUID battle_id = 2;
  google.protobuf.Any location = 3;
}

message HeroStartBattleHeroDTO {
  string hero_definition_id = 1;
  int32 battlefield_slot = 2;
  bool has_support_unit = 3;
}

message HeroStartBattleResponse {
  HeroBattleDataDTO battle_data = 1;
}

message HeroCancelBattleRequest {
  UUID battle_id = 2;
}

message RecordedBattleAction {
  message TriggerAbilityForUnit {
    int32 unit_id = 1;
  }
  int64 time_old = 1;
  FixedPointDTO trigger_ability_for_unit = 2;
  FixedPointDTO try_toggle_auto_battle = 3;
  FixedPointDTO time = 4;
}

message HeroFinishWaveRequest {
  UUID battle_id = 2;
  HeroBattleLogDTO stats_after_wave = 3;
  HeroBattleLogDTO battle_log = 4;
  bool used_auto_battle = 6;
  float battle_speed = 7;
  int64 recorded_actions = 8;
  int64 last_update_time_old = 9;
  FixedPointDTO last_update_time = 10;
}

message HeroUnitStatsUpdateDTO {
  string stat_definition_id = 1;
}

message HeroFinishWaveResponse {
  UUID battle_id = 1;
  HeroBattleDataDTO battle_data = 2;
}

message HeroStartWaveRequest {
  UUID battle_id = 2;
}

message HeroBattleDataDTO {
  UUID battle_id = 1;
  HeroBattleResult result = 2;
  google.protobuf.Any location = 3;
  string battlefield_definition_id = 4;
  int32 wave = 5;
}

message HeroBattleSquadDTO {
  int32 battlefield_slot = 1;
  HeroBattleUnitDTO hero_unit = 2;
  HeroBattleUnitGroupDTO supporting_unit = 3;
  int32 wave = 4;
}

message HeroBattleUnitDTO {
  HeroUnitDTO unit = 1;
  HeroBattleUnitDataDTO unit_data = 2;
}

message HeroBattleUnitGroupDTO {
  HeroUnitDTO unit = 1;
}

message HeroBattleUnitDataDTO {
  int32 id_in_battle = 1;
}

message HeroUnitDTO {
  string definition_id = 1;
  int32 level = 2;
  int32 ascension_level = 3;
  bool stat_boosts = 6;
  bool domain_data = 7;
  bool repeat_last_ability = 8;
  int32 ability_level = 9;
  int32 awakening_level = 10;
  string star_up_definition_id = 11;
}

message HeroBattleLogsDTO {
}

message HeroBattleConstantsDefinitionDTO {
  string id = 1;
  google.protobuf.Duration max_battle_duration = 2;
  AttackCalculationValuesDTO attack_calculation_values = 3;
  string formula_fallback_by_stat = 4;
  string fallback_formula_definition_id = 5;
  float unit_stat_fallbacks = 6;
  float speed_up_option_feature = 8;
  float speed_up_option_benefit = 9;
  bool use_bidirectional_color_factor = 10;
  float splash_damage_exponent = 11;
  JoystickBattleConfigDTO status_effect_interactions_ids = 12;
  JoystickBattleConfigDTO joystick_battle_config = 13;
}

message JoystickBattleConfigDTO {
  float influence_circle_radius = 1;
  float min_follower_distance = 2;
  float max_follower_distance = 3;
  float min_follower_spacing = 4;
}

message AttackCalculationValuesDTO {
  float min_random_attack_factor = 1;
  float max_random_attack_factor = 2;
  float attack_exponent = 3;
}

message HeroBattleDefinitionDTO {
  string definition_id = 1;
  string battlefield_asset_set_definition_id = 2;
  string battle_wave_definition_ids = 3;
  string battlefield_preset_definition_id = 4;
}

message HeroBattleWaveDefinitionDTO {
  string definition_id = 1;
}

message HeroBattleHeroAndSupportUnitDTO {
  int32 battlefield_slot = 1;
  HeroUnitDTO hero_unit = 2;
  HeroUnitDTO supporting_unit = 3;
}

message BattlefieldPresetDefinitionDTO {
  string definition_id = 1;
  google.protobuf.Duration slotted_player_unit_ability_definition_ids = 6;
  google.protobuf.Duration max_battle_duration_override = 7;
  google.protobuf.Any win_conditions = 8;
  google.protobuf.Any lose_conditions = 9;
  google.protobuf.Any battle_result_calculation = 10;
  bool battle_boosts = 11;
  bool has_support_squad = 12;
  HeroBattleUnitStyle player_unit_style = 13;
  HeroBattleUnitStyle enemy_unit_style = 14;
  bool allow_player_input = 15;
  bool pause_for_enemy_abilities = 16;
  bool wait_for_active_abilities_on_battle_end = 17;
  float player_unit_rotation = 18;
  float enemy_unit_rotation = 19;
}

message BattleBoostDTO {
  HeroTaskFilterDTO filter = 1;
  bool boosts = 2;
  bool apply_to_support_units = 3;
}

message PlayerHeroSurvivorCalculationDTO {
}

message PlayerUnitHitPointCalculationDTO {
  message StarsByRemainingHitPointPercentDTO {
    float key = 1;
    int32 value = 2;
  }
  google.protobuf.Any filter = 1;
}

message RemainingTimeCalculationDTO {
  message StarsByRemainingTimeDTO {
    google.protobuf.Duration key = 1;
    int32 value = 2;
  }
}

message BattleTimerExpiredConditionDTO {
}

message UnitsDeadConditionDTO {
  enum ModeDTO {
    ALL = 0;
    ANY = 1;
  }
  google.protobuf.Any filter = 1;
  ModeDTO mode = 2;
}

message UnitsOnLaneDeadConditionDTO {
  google.protobuf.Any filter = 1;
}

message BattlefieldLaneDefinitionDTO {
  string definition_id = 1;
  int32 lane_index = 2;
}

message BattleFieldAssetSetDefinitionDTO {
  string definition_id = 1;
  string start = 2;
  string middle = 3;
  string end = 4;
}

message BattlefieldSpawnPointDTO {
  int32 id = 1;
  int32 x = 2;
  int32 y = 3;
  bool is_outside_of_battlefield = 4;
  int32 attack_priority = 5;
}

message BattlefieldSlotDTO {
  int32 id = 1;
  int32 x = 2;
  int32 y = 3;
  int32 order = 6;
}

message BattlefieldLocationPointDTO {
  int32 x = 1;
  int32 y = 2;
}

message HeroBattleLocationTypeWrapper {
  enum HeroBattleLocationTypeDTO {
    CAMPAIGN = 0;
    QUEST = 2;
    TASK_POOL = 3;
    PVP = 4;
    HERO_TREASURE_HUNT = 5;
    HERO_DEMO = 6;
    TESLA_STORM = 7;
    HISTORIC_BATTLE = 8;
    WAR_OF_ATLANTIS = 9;
    PVP_REVENGE = 10;
    BATTLE_EVENT = 11;
  }
}

message BattleValidationErrorPush {
  string error = 1;
}

message UnitStatAttributeDefinitionDTO {
  enum CalculationTypeDTO {
    ADD = 0;
    MULTIPLY = 1;
    FACTOR_STAT_ADD = 2;
    SOURCE_MULTIPLY = 3;
  }
  string definition_id = 1;
  int32 order = 2;
  CalculationTypeDTO calculation = 3;
  string unit_stat_definition_id = 4;
  string factor_unit_stat_definition_id = 5;
}

message UnitStatBoostDTO {
  int32 order = 1;
  CalculationTypeDTO calculation = 2;
  string unit_stat_definition_id = 3;
  float value = 4;
  string factor_unit_stat_definition_id = 5;
  string unit_stat_attribute_definition_id = 6;
  UnitStatBoostSourceDTO source_stats = 7;
  UnitStatBoostSourceDTO source = 8;
}

message BattleSuggestionComponentDTO {
  int32 suggested_power = 1;
}

message EnemyPreviewComponentDTO {
}

message BattleHeroIndicatorComponentDTO {
}

message EnemyPreviewDTO {
  int32 lane_index = 1;
  string unit_color_definition_id = 2;
  string asset_id = 3;
  int32 weakness_percentage = 5;
  string weakness_status_effect_id = 6;
  bool boss = 7;
  bool show_color_background = 8;
}

message HeroBattleStatsRequest {
  UUID battle_uuid = 2;
}

message HeroBattleStatsResponse {
  message SquadStatsDTO {
    UnitStatDTO hero_stats = 1;
    UnitStatDTO support_unit_stats = 2;
  }
  message UnitStatDTO {
    string unit_definition_id = 1;
    float damage_dealt = 2;
    float damage_taken = 3;
    float healed = 4;
  }
  UUID battle_uuid = 1;
}

message FixedPointDTO {
  int64 raw_value = 1;
}
