syntax = "proto3";

package InnoGames.Generated.Protobuf;

message HeroUnitDefinitionDTO {
  string id = 1;
  string asset_id = 2;
  string unit_type = 3;
  string unit_color = 4;
  string components = 6;
  string unit_icon_override = 7;
  bool display_as_hero = 8;
}

message HeroUnitStatDefinitionDTO {
  string id = 1;
  bool hidden = 2;
  bool tracked_between_waves = 3;
  int32 order = 4;
  string group = 5;
}

message HeroUnitStatConfigDefinitionDTO {
  enum UnitStatFormattingType {
    NUMERIC = 0;
    PERCENTAGE = 1;
    CUSTOM = 2;
  }
  string definition_id = 1;
  string unit_stat = 2;
  string battle_start_unit_stat = 3;
  string max_unit_stat = 4;
  Nullable<double> min = 5;
  string regen_unit_stat = 6;
  UnitStatFormattingType formatting_type = 7;
}

message HeroUnitStatValueDefinitionDTO {
  string id = 1;
  string stat_definition_id = 2;
  float value = 3;
  string formula_definition_id = 4;
}

message HeroUnitColorDefinitionDTO {
  string id = 1;
}

message HeroUnitRarityDefinitionDTO {
  string id = 1;
}

message HeroUnitTypeDefinitionDTO {
  string id = 1;
  bool fallback_stats = 2;
  bool filterable = 3;
  bool excluded_from_battle_end = 4;
}

message HeroUnitStatFormulaDefinitionDTO {
  string id = 1;
  HeroUnitStatFormulaParametersDTO fallback = 2;
}

message HeroUnitStatFormulaParametersDTO {
  float level_factor = 1;
  float ascension_level_factor = 2;
}

message HeroUnitStatFormulaTermDTO {
  string unit_stat_definition_id = 1;
  double factor = 2;
}

message HeroUnitStatUnboostedFormulaTermDTO {
  string unit_stat_definition_id = 1;
  double factor = 2;
}

message HeroUnitLevelFormulaTermDTO {
  double factor = 1;
}

message HeroUnitRarityFormulaTermDTO {
  double factors_by_unit_rarity = 1;
  double fallback = 2;
}

message UnitStatLabelsDTO {
  message UnitStatLabelDTO {
    string label = 1;
    double upper_bound = 2;
  }
}
