syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "init.proto";
import "resource.proto";

message UnlockPantheonNodeRequest {
  string hero_definition_id = 1;
  string node_definition_id = 2;
}

message ResetPantheonTreeRequest {
  string hero_definition_id = 1;
  PartialPaymentDTO invested_premium = 2;
}

message HeroPantheonStatePush {
}

message HeroPantheonStateDTO {
  string hero_definition_id = 1;
}

message PantheonActivatedNodeDTO {
  string node_definition_id = 1;
  int32 level = 2;
}

message HeroPantheonFreeNodeDTO {
  string hero_definition_id = 1;
  int32 free_nodes = 2;
  int32 layer = 3;
}

message HeroPantheonNodeUpdatedPush {
  string hero_definition_id = 1;
  PantheonActivatedNodeDTO node = 2;
}

message HeroPantheonResetPush {
  string hero_definition_id = 1;
}

message PantheonUnitVODataDTO {
}

message PantheonBlueprintDefinitionDTO {
  string id = 1;
}

message PantheonLayerConfigDTO {
  int32 layer_index = 1;
}

message PantheonNodeDefinitionDTO {
  string id = 1;
  int32 position = 3;
  string levels = 4;
  string asset_id = 5;
}

message PantheonNodeLevelDTO {
  ActionComponentDTO select_action = 1;
}

message PantheonLayerNodesRequirementDTO {
  int32 layer_index = 1;
  int32 min_nodes = 2;
  int32 max_nodes = 3;
  int32 min_node_levels = 4;
  int32 max_node_levels = 5;
}

message HeroRarityRequirementDTO {
}
