syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/any.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
import "init.proto";
import "resource.proto";
import "reward.proto";

enum InGameEventStateDTO {
  BLOCKED = 0;
  PREPARED = 1;
  ACTIVE = 2;
  ENDED = 3;
  DISMISSED = 4;
}

enum EventPointSeenKey {
  START = 0;
  END = 1;
}

enum ShowHudAccessButtonModeDTO {
  ALLOW = 0;
  NEVER = 1;
  ALWAYS = 2;
}

message InGameEventUpdateContextDTO {
  int64 event_id = 1;
}

message EventUpdateContextDTO {
  int64 event_id = 1;
}

message GetEventRequest {
  int64 event_id = 1;
}

message DismissEventRequest {
  int64 event_id = 1;
}

message EventUpdatedDTO {
  int64 event_id = 1;
  google.protobuf.Timestamp start = 3;
  google.protobuf.Timestamp end = 4;
  google.protobuf.Timestamp expiry = 5;
}

message InGameEventPush {
}

message InGameEventDTO {
  int64 id = 1;
  EventDefinitionDTO definition = 2;
  google.protobuf.Timestamp start = 3;
  google.protobuf.Timestamp end = 4;
  google.protobuf.Timestamp expiry = 5;
  InGameEventStateDTO state = 6;
}

message EventDefinitionDTO {
  string id = 1;
  string components = 2;
  string requirements = 3;
  string asset_id = 4;
}

message OpenChestEventChestRequest {
  int64 event_id = 1;
  string event_definition_id = 2;
  string group = 3;
  int32 amount = 5;
}

message ChestEventDefinitionDTO {
  string id = 1;
}

message ChestEventGroupDefinitionDTO {
  string id = 1;
}

message ChestEventDTO {
}

message ChestEventChestDTO {
  string group_definition_id = 1;
  ActionComponentDTO action = 2;
  int64 seed = 3;
}

message OpenEventChestTaskDTO {
  string id = 1;
  int64 amount = 2;
}

message EventShopDefinitionDTO {
  string event_definition_id = 1;
  string offers = 2;
  string premium_tracking_main_type = 3;
}

message EventShopOfferDefinitionDTO {
  string id = 1;
}

message BuyEventShopOfferRequest {
  string event_definition_id = 2;
  string offer_id = 3;
}

message EventDailyLoginDTO {
  google.protobuf.Timestamp daily_end_at = 1;
  bool daily_claimed = 2;
  google.protobuf.Any reward = 3;
}

message ClaimDailyLoginRequest {
  int64 event_id = 1;
  string login_reward_definition_id = 2;
}

message QuestlineEventDTO {
  string id = 1;
  string event_definition_id = 2;
  google.protobuf.Timestamp start_at = 3;
  google.protobuf.Timestamp end_at = 4;
  int32 event_day = 5;
}

message EventDailyLoginRewardDefinitionDTO {
  string id = 1;
}

message QuestlineEventRequirementDTO {
}

message QuestlineEventDefinitionDTO {
  string id = 1;
}

message EventDailySpecialDefinitionDTO {
  string id = 1;
}

message EventDailySpecialDTO {
  int32 event_day = 1;
  google.protobuf.Any reward = 2;
}

message EventRankingBracketComponentDTO {
  string id = 1;
  float threshold = 2;
}

message EventRankingDefinitionDTO {
  string id = 1;
  ResourceDefinitionDTO progress_resource = 3;
}

message EventRankingStateDTO {
  int64 progress_at_event_end = 1;
  string bracket_at_event_end = 2;
}

message EventRankingThresholdsDTO {
  string id = 1;
}

message PlayerEventRankingDTO {
  int32 player_id = 1;
  string definition_id = 2;
  int64 progress = 3;
}

message GetPlayerEventRankingRequest {
  int64 event_id = 1;
}

message PlayerEventRankingUpdatedDTO {
  PlayerEventRankingDTO player_event_ranking = 1;
  EventRankingThresholdsDTO thresholds = 2;
}

message EventSeenDTO {
}

message EventShopOfferSeenDTO {
  string offer_id = 1;
  google.protobuf.Timestamp seen_at = 2;
}

message EventSeenComponentDTO {
  string id = 1;
}

message ShopOfferEventComponentDTO {
}

message MarkStartScreenSeenRequest {
  int64 event_id = 2;
  string component_id = 3;
}

message MarkPointSeenRequest {
  int64 event_id = 1;
  string component_id = 2;
  EventPointSeenKey point = 3;
}

message MarkShopOfferSeenRequest {
  int64 event_id = 1;
  string component_id = 2;
  string offer_id = 3;
}

message EventResourceComponentDTO {
  string id = 1;
}

message EventPityComponentDTO {
  string id = 1;
}

message TriggerInGameEventRewardDTO {
  BaseRewardDTO base_data = 1;
  EventDefinitionDTO event = 2;
  google.protobuf.Duration start_in = 3;
  google.protobuf.Duration duration = 4;
}

message EventActiveRequirementDTO {
  string id = 1;
}

message EventDisplayComponentDTO {
  string id = 1;
  string event_task_id = 2;
  string vfx_id = 3;
  string video_url = 4;
  bool has_start_screen = 5;
  string portal_asset_theme_id = 6;
  string tutorial_teaser_asset_id = 7;
  int32 display_priority = 8;
  ShowHudAccessButtonModeDTO show_hud_access_mode = 9;
  string linked_event_definitions = 10;
  string calendar_url = 11;
}
