syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/any.proto";

message ServerMessageResponse {
  string message = 1;
  bool show_to_player = 2;
}

message ClientReloadPush {
  string message = 1;
  int32 max_delay = 2;
  bool clear_gd_cache = 3;
  bool clear_loca_cache = 4;
}

message InitComponentDTO {
  string id = 1;
}

message ActionComponentDTO {
  string requirements = 1;
  string rewards = 2;
  string dynamic_change_definition_id = 3;
}

message DynamicActionChangeDefinitionDTO {
  string id = 1;
}

message DynamicFloatValueDefinitionDTO {
  string id = 1;
  google.protobuf.Any mapping = 2;
}

message DynamicFloatValueDTO {
  float value = 1;
  string dynamic_value_definition_id = 2;
}

message ActionChangeDTO {
}

message DynamicChangeCaseDTO {
  string when = 1;
  google.protobuf.Any then = 2;
}

message PlayerAgeDynamicChangeDTO {
}

message TreasureHuntAgeDynamicChangeDTO {
}

message BuildingAgeDynamicChangeDTO {
}

message BuildingLevelDynamicChangeDTO {
}

message WonderTagDynamicChangeDTO {
  string values = 1;
  string tag = 2;
}

message SeasonPassAgeDynamicChangeDTO {
  string values = 1;
  string event = 2;
  string season_pass_group = 3;
}

message EventIdDynamicChangeDTO {
}
