syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/any.proto";
import "google/protobuf/duration.proto";
import "reward.proto";

message InventoryEntryDTO {
  int64 amount = 2;
  string definition_id = 4;
}

message InventoryDTO {
}

message InventoryUpdateDTO {
}

message InventoryItemDefinitionDTO {
  string definition_id = 1;
}

message UseItemRequest {
  string definition_id = 2;
  google.protobuf.Any selected_target = 3;
}

message InventoryItemRewardDTO {
  string definition = 1;
  int32 amount = 2;
  BaseRewardDTO base_data = 3;
}

message InventoryEntryRewardDTO {
  string definition = 1;
  int32 amount = 2;
  BaseRewardDTO base_data = 3;
}

message SyncResourcesRequest {
  string resource_type = 2;
}

message StorageCapTraitDTO {
  int64 affected_actions = 1;
  int64 base_capacity = 2;
  string subscription_benefit = 3;
  float subscription_capacity_multiplier = 4;
}

message StorageCapTraitDataDTO {
  int64 from_rewards = 1;
}

message GameRegeneratingTraitTimeSkipRewardDTO {
  string resource_definition_id = 1;
  google.protobuf.Duration duration = 2;
  BaseRewardDTO base_data = 3;
}

message GameRegeneratingTraitMaxCapRewardDTO {
  string resource_definition_id = 1;
  int64 amount = 2;
  BaseRewardDTO base_data = 3;
}

message EventBasedRegenerationStartRewardDTO {
  string resource_definition_id = 1;
  string event = 2;
  google.protobuf.Duration offset = 3;
  BaseRewardDTO base_data = 4;
}
