syntax = "proto3";

package InnoGames.Generated.Protobuf;

enum LimitType {
  LimitType_LIMIT_TRADING_TOKENS = 0;
  LimitType_LIMIT_TRADING_GOODS = 1;
}

message DynamicLimitDefinitionDTO {
  string definition_id = 1;
  int64 max = 2;
  int64 min = 3;
}

message DynamicLimitDTO {
  int64 max = 1;
  int64 min = 2;
  LimitType type = 3;
}

message DynamicLimitsDTO {
}

message IncreaseLimitRewardDTO {
  int64 max_increase = 1;
  int64 min_increase = 2;
  LimitType type = 3;
}

message DynamicLimitTraitDTO {
  string definition_id = 1;
}
