syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/timestamp.proto";

message LoginEventDefinitionDTO {
  enum RewardGrantModeDTO {
    LINEAR = 0;
    CUMULATIVE = 1;
    SPECIFIC_PERIOD = 2;
  }
  string id = 1;
  string period_cron = 2;
  RewardGrantModeDTO reward_mode = 3;
}

message LoginEventStateDTO {
  int32 unique_login_count = 1;
  google.protobuf.Timestamp last_login_at = 2;
  google.protobuf.Timestamp next_unlock_time = 3;
}

message CollectLoginEventRewardRequest {
  int64 event_id = 1;
  string login_event_definition_id = 2;
  int32 reward_day = 3;
}
