syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/any.proto";
import "uuid.proto";

enum NegotiationGameState {
  NegotiationGameState_RUNNING = 0;
  NegotiationGameState_WON = 1;
  NegotiationGameState_OUT_OF_TURNS = 2;
  NegotiationGameState_CANCELED = 3;
}

enum NegotiationGameSlotResult {
  NegotiationGameSlotResult_CORRECT = 0;
  NegotiationGameSlotResult_OTHER = 1;
  NegotiationGameSlotResult_NOT_INCLUDED = 2;
}

message NegotiationGameStartRequest {
  google.protobuf.Any location = 2;
}

message NegotiationGameDTO {
  UUID game_id = 1;
  google.protobuf.Any location = 2;
  NegotiationGameState state = 3;
  int32 possible_gifts = 4;
  int32 turns_left = 5;
}

message ResourceGiftDTO {
  string resource_id = 1;
  int64 amount = 2;
}

message GoodGiftDTO {
  int32 number = 2;
  int64 amount = 3;
  int32 offset = 4;
}

message NegotiationGameTurnDTO {
  int32 turn_index = 1;
}

message SlotResultDTO {
  int32 slot = 1;
  string gift_id = 2;
  NegotiationGameSlotResult result = 3;
}

message SubmitNegotiationGameTurnRequest {
  UUID game_id = 1;
}

message OfferedGiftDTO {
  int32 slot = 1;
  string gift_id = 2;
  int64 invested_premium = 3;
}

message CancelNegotiationGameRequest {
  UUID game_id = 2;
}

message BuyNegotiationGameTurnRequest {
  UUID game_id = 2;
  int64 invested_premium = 3;
}

message NegotiationGameGiftsDefinitionDTO {
  string id = 1;
  google.protobuf.Any mapping = 2;
}

message GiftDefinitionDTO {
  google.protobuf.Any gift = 1;
}

message NegotiationGameComponentDTO {
  string id = 1;
  int32 turns = 2;
}

message NegotiationGiftDTO {
  NegotiationGameGiftsDefinitionDTO gift = 1;
  float factor = 2;
}

message NegotiationGameDefinitionDTO {
  string id = 1;
  google.protobuf.Any game_component = 2;
}

message NegotiationCheatCorrectGiftDTO {
  int32 slot = 1;
  string gift_id = 2;
}

message NegotiationCheatCorrectCombinationDTO {
}
