syntax = "proto3";

package InnoGames.Generated.Protobuf;

enum SettingsTypeEnum {
  PREMIUM_CONFIRMATION = 0;
  PUSH_NOTIFICATIONS_DISABLED = 1;
  APP_RATING_SEEN_COUNT = 100;
  SHOP_OFFER_HERO = 101;
  USE_DTC_PAYMENT = 102;
  LAST_DTC_OFFERED_TIME = 103;
  LAST_PLAYER_AVATAR_OPEN_DATE = 104;
  WOA_INTRO_CAROUSEL_SEEN = 105;
}

message PlayerSettingsPush {
}

message UpdateEnumSettingsRequest {
  SettingsTypeEnum type = 1;
  int32 enum_value = 2;
  bool active = 3;
}

message UpdateStringSettingsRequest {
  SettingsTypeEnum type = 1;
  string value = 2;
}

message PlayerEnumSettingsDTO {
  SettingsTypeEnum type = 1;
}

message PlayerStringSettingsDTO {
  SettingsTypeEnum type = 1;
  string value = 2;
}
