syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "expansion_type.proto";
import "google/protobuf/timestamp.proto";
import "init.proto";
import "resource.proto";
import "taskpool.proto";
import "worker.proto";

enum QuestlineState {
  QuestlineState_UNSEEN = 0;
  QuestlineState_ACCEPTED = 1;
  QuestlineState_COMPLETABLE = 2;
  QuestlineState_COMPLETED = 3;
}

enum WonderResearchPointTarget {
  WonderResearchPointTarget_ANY = 0;
  WonderResearchPointTarget_OWN = 1;
  WonderResearchPointTarget_OTHER = 2;
}

enum RelativeAge {
  RelativeAge_CURRENT = 0;
  RelativeAge_PREVIOUS = 1;
  RelativeAge_PREVIOUS_OR_CURRENT = 2;
}

enum ProductionTime {
  ProductionTime_ALL = 0;
  ProductionTime_SHORT = 2;
  ProductionTime_MEDIUM = 3;
  ProductionTime_LONG = 4;
}

message QuestlineDefinitionDTO {
  string id = 1;
  string age = 2;
  int32 order = 3;
  bool hidden = 4;
  string components = 5;
  string cities = 6;
  string group = 7;
}

message QuestlineCollectionDefinitionDTO {
  string id = 1;
  int32 order = 2;
  string hex_color = 3;
}

message QuestlineDTO {
  int64 id = 1;
  string definition_id = 2;
  QuestlineState state = 3;
  string quest_component_id = 4;
  google.protobuf.Timestamp progress = 5;
  google.protobuf.Timestamp last_updated = 6;
  google.protobuf.Timestamp accepted_at = 7;
  int64 event_id = 8;
}

message QuestlinesDTO {
}

message QuestlineDeletedDTO {
  QuestlineDTO questline = 1;
}

message QuestlineComponentDTO {
  string id = 1;
  ActionComponentDTO start = 2;
  ActionComponentDTO finish = 3;
}

message QuestComponentDTO {
  string id = 1;
  string quest_giver = 2;
  int32 order = 3;
  ActionComponentDTO finish = 4;
  bool tasks = 5;
  bool or_condition = 6;
  bool is_optional = 7;
}

message QuestlineCompletedRequirementDTO {
  string id = 1;
}

message EventDayActiveRequirementDTO {
  string id = 1;
  int32 day = 2;
}

message DefeatEnemyUnitsTaskDTO {
  string id = 1;
  int64 amount = 2;
  string unit_type_definition_id = 3;
  bool only_heroes = 4;
  string unit_color_definition_id = 5;
  bool with_instant_play = 6;
}

message AcceptQuestRequest {
  string id = 1;
}

message CompleteQuestRequest {
  string id = 1;
  ExpectedTaskProgressionDTO expected_progress = 3;
}

message PartialPayQuestRequest {
  string id = 1;
  string task_id = 2;
  ResourceDTO invest_resource = 5;
  int64 invested_premium = 6;
  PartialPaymentType partial_payment_type = 7;
}

message HaveBuildingTaskDTO {
  string id = 1;
  string building_definition_id = 3;
  int64 amount = 4;
  string building_type = 5;
  string age = 6;
  string city = 7;
  bool retrospective = 8;
  string resource = 9;
  string building_group = 10;
  int32 building_level = 11;
  bool is_minimum_level = 12;
}

message CollectResourceTaskDTO {
  string id = 1;
  int64 amount = 2;
  string resource_definition_id = 3;
  string building_type = 4;
  string city_definition_id = 5;
  string age = 6;
  string building_definition_id = 7;
  string building_group = 8;
  string dynamic_change_definition_id = 9;
  string resource_type = 10;
}

message SpendResourceTaskDTO {
  string id = 1;
  int64 amount = 2;
  string resource_definition_id = 3;
}

message ResearchTechnologyTaskDTO {
  string id = 1;
  int64 amount = 2;
  string technology_definition_id = 3;
  string city_definition_id = 4;
  string age = 5;
  string city = 6;
}

message ProductionTaskDTO {
  string id = 1;
  int64 amount = 2;
  bool is_collect = 3;
  string resource_definition_id = 4;
  string city_definition_id = 5;
  string building_type = 6;
  string building_group = 7;
  string age = 8;
  string building_definition_id = 9;
  bool auto_production = 10;
}

message HaveWorkerTaskDTO {
  string id = 1;
  int64 amount = 2;
  string city_definition_id = 3;
  bool retrospective = 4;
  WorkerType worker_type = 5;
}

message UnlockExpansionTaskDTO {
  string id = 1;
  int64 amount = 2;
  string expansion_id = 3;
  string city_definition_id = 4;
  ExpansionSubType expansion_sub_type = 5;
}

message SolveIncidentsTaskDTO {
  string id = 1;
  int64 amount = 2;
}

message HaveResourceTaskDTO {
  string id = 1;
  int64 amount = 2;
  string resource_definition_id = 3;
  string resource_type = 4;
  string city_definition_id = 5;
  string age = 6;
}

message HaveHappyBuildingsTaskDTO {
  string id = 1;
  int64 amount = 2;
  int32 happiness_level = 3;
  string building_definition_id = 4;
  string building_type = 5;
  string building_group = 6;
  string age = 7;
  string city_definition_id = 8;
  string resource = 9;
}

message PayResourceTaskDTO {
  string id = 1;
  ResourceDTO resource = 4;
  string dynamic_change_definition_id = 5;
}

message WondersSpendResearchPointsTaskDTO {
  string id = 1;
  int64 amount = 2;
  WonderResearchPointTarget target = 4;
}

message SpendResearchPointsTaskDTO {
  string id = 1;
  int64 amount = 2;
}

message HaveAllianceTaskDTO {
  string id = 1;
  int64 amount = 2;
}

message CollectWorkerProductionTaskDTO {
  string id = 1;
  int64 amount = 2;
  RelativeAge relative_age = 3;
  string city = 4;
  string building_type = 5;
  string building_group = 6;
  ProductionTime production_time = 7;
}

message QuestBattleTaskDTO {
  string id = 1;
  int64 amount = 2;
  string battlefield_definition_id = 3;
}

message QuestlineLocationDTO {
  string task_id = 1;
}

message NegotiationTaskDTO {
  string id = 1;
  string negotiation_game_definition_id = 4;
}

message QuestNegotiationGameStartRequest {
  string quest_task_id = 2;
}

message FinishBattleTaskDTO {
  string id = 1;
  int64 amount = 2;
  bool allow_defeat = 3;
}

message WinConsecutiveBattleTaskDTO {
  string id = 1;
  int64 amount = 2;
}

message WinBattleWithoutUnitTaskDTO {
  string id = 1;
  int64 amount = 2;
  string unit_type_definition_id = 3;
}

message WinBattleWaveWithHeroTaskDTO {
  string id = 1;
  int64 amount = 2;
  string hero_definition_id = 3;
}

message WonderContributionTaskDTO {
  string id = 1;
  int64 amount = 2;
}

message WonderInventionTaskDTO {
  string id = 1;
  int64 amount = 2;
}

message HaveWonderActiveTaskDTO {
  string id = 1;
  int64 amount = 2;
}

message SolveQuestsTaskDTO {
  string id = 1;
  int64 amount = 2;
  string taskpool_selector_definition_id = 3;
}

message CrossSellingTaskDTO {
  string id = 1;
}

message ReachPvpTierTaskDTO {
  string id = 1;
  int64 amount = 2;
  string pvp_tier_history_group = 3;
  string pvp_event_tier_definition_id = 4;
}

message QuestBattleLocationDTO {
  string questline_definition_id = 1;
  string quest_task_id = 2;
}

message PreSolvedTaskDTO {
  string id = 1;
  int64 amount = 2;
}

message LoginOnPlatformTaskDTO {
  string id = 1;
  int64 amount = 2;
}

message InitialRenamePlayerTaskDTO {
  string id = 1;
  int64 amount = 2;
}
