syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "alliance.proto";
import "alliance_banner.proto";
import "google/protobuf/timestamp.proto";

enum RankingType {
  RankingType_RESEARCH_POINTS = 0;
  RankingType_TOTAL = 1;
  RankingType_SEASON_PASS_PROGRESS = 6;
  RankingType_EVENT_CITY_PROGRESS = 8;
  RankingType_TOTAL_HERO_POWER = 9;
}

enum AllianceRankingType {
  AllianceRankingType_UNKNOWN = 0;
  AllianceRankingType_MEMBER_TOTAL = 1;
  AllianceRankingType_TOTAL = 2;
  AllianceRankingType_TREASURE_HUNT_TOTAL = 3;
  AllianceRankingType_TREASURE_HUNT_1ST = 4;
  AllianceRankingType_TREASURE_HUNT_2ND = 5;
  AllianceRankingType_TREASURE_HUNT_3RD = 6;
  AllianceRankingType_ALLIANCE_RESEARCH_POINTS_TOTAL = 7;
  AllianceRankingType_ALLIANCE_RESEARCH_POINTS_COMMON = 8;
  AllianceRankingType_ALLIANCE_RESEARCH_POINTS_RARE = 9;
  AllianceRankingType_ALLIANCE_RESEARCH_POINTS_EPIC = 10;
}

message PlayerRankDTO {
  int32 player_id = 1;
  string name = 2;
  int32 portrait_id = 3;
  string age = 4;
  string alliance_name = 5;
  int32 rank = 6;
  int64 score = 7;
}

message PlayerRanksDTO {
  google.protobuf.Timestamp player_position = 2;
  google.protobuf.Timestamp next_calculation_at = 3;
  RankingType combined_ranking_data = 4;
  RankingType ranking_type = 5;
}

message AllianceRankDTO {
  int64 alliance_id = 1;
  int32 rank = 2;
  int64 score = 3;
  int32 member_count = 4;
  string name = 5;
  int32 icon_id = 6;
  int32 crest_id = 7;
  int32 max_members = 8;
  AllianceAdmissionType admission = 9;
  string locale = 10;
  AllianceMemberDTO leader = 11;
  string description = 12;
  AlliancePlaystyleType recent_members = 13;
  AlliancePlaystyleType playstyle = 14;
  string required_age = 15;
  int32 required_total_power = 16;
  int32 required_treasure_hunt_difficulty = 17;
  AllianceBannerDTO banner = 18;
}

message AllianceRanksDTO {
  google.protobuf.Timestamp player_position = 2;
  google.protobuf.Timestamp next_calculation_at = 3;
  AllianceRankingType combined_ranking_data = 4;
  AllianceRankingType alliance_ranking_type = 5;
}

message GetRankingRequest {
  RankingType ranking = 1;
}

message GetAllianceRankingRequest {
  AllianceRankingType ranking = 1;
  bool filter_admission = 2;
  AllianceAdmissionType admission = 3;
  int32 min_free_slots = 4;
}

message CombinedPlayerRankingDefinitionDTO {
  string id = 1;
  RankingType ranking = 2;
  bool combined_rankings = 3;
  bool display_sub_rankings = 4;
}

message CombinedPlayerRankingComponentDTO {
  RankingType ranking = 1;
  double factor = 2;
}

message CombinedPlayerRankingDTO {
  RankingType ranking = 1;
}

message CombinedAllianceRankingDefinitionDTO {
  string id = 1;
  AllianceRankingType ranking = 2;
  bool combined_rankings = 3;
  bool display_sub_rankings = 4;
}

message CombinedAllianceRankingComponentDTO {
  AllianceRankingType ranking = 1;
  double factor = 2;
}

message CombinedAllianceRankingDTO {
  AllianceRankingType ranking = 1;
}

message PlayerRankingTraitDTO {
  RankingType ranking = 1;
}
