syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "gamedesign_enums.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
import "uuid.proto";

enum PartialPaymentType {
  PartialPaymentType_PAY_NO_PREMIUM = 0;
  PartialPaymentType_PAY_ALL_WITH_PREMIUM = 1;
  PartialPaymentType_PAY_REST_WITH_PREMIUM = 2;
}

message ResourceDefinitionDTO {
  string id = 1;
  string traits = 2;
  string resource_type = 3;
  string age = 4;
  int64 cities = 5;
  int64 order = 6;
}

message ResourceDTO {
  string definition_id = 1;
  int64 amount = 2;
  bool traits = 3;
  bool partially_payable = 4;
  bool from_resource_change = 5;
}

message ResourceDataDTO {
  string definition_id = 1;
  int64 amount = 2;
}

message PartialPaymentProgressDTO {
  string payment_target_id = 1;
  string payment_component_id = 2;
}

message PartialPaymentsProgressDTO {
}

message PartialPaymentDTO {
  PartialPaymentType partial_payment_type = 1;
}

message PartialPaymentCost {
  string cost_id = 1;
  int64 amount = 2;
}

message PartialPaymentResultDTO {
  string definition_id = 1;
  int64 owner_id = 2;
}

message GetPartialPaymentsRequest {
  string definition_id = 1;
}

message NotSmallerZeroTraitDTO {
}

message InventoryDisplayTraitDTO {
  InventoryDisplayType type = 1;
  int32 order = 2;
}

message IncreaseResourceCapacityAwareTraitDTO {
}

message ResourceCapNotReachedRequirementDTO {
  string resource = 1;
}

message HaveResourceRequirementDTO {
  string resource = 1;
  int64 amount = 2;
}

message CappingTraitDTO {
  int64 min = 1;
  int64 max = 2;
}

message PremiumTraitDTO {
}

message RegeneratingTraitDTO {
  int64 max = 1;
  float amount_per_unit = 2;
  google.protobuf.Duration duration = 3;
  bool is_reset = 4;
}

message RegeneratingTraitDataDTO {
  google.protobuf.Timestamp last_update = 1;
}

message CronRegeneratingTraitDTO {
  int64 max = 1;
  float amount_per_unit = 2;
  string cron = 3;
  google.protobuf.Timestamp next_regeneration = 4;
}

message CronRegeneratingTraitDataDTO {
  google.protobuf.Timestamp last_update = 1;
  google.protobuf.Timestamp next_update = 2;
}

message GameRegeneratingTraitDataDTO {
  google.protobuf.Timestamp last_update = 1;
  google.protobuf.Duration remaining_time = 2;
  bool completed = 3;
  int64 from_rewards = 4;
  google.protobuf.Timestamp start_time = 5;
}

message GoodRequirementDTO {
  string id = 1;
}

message AgeRequirementDTO {
  string id = 1;
  string max_age_definition = 2;
  string min_age_definition = 3;
}

message ConversionTraitDTO {
  string resource = 1;
}

message ConversionAgeFactorDTO {
  string age = 1;
  float factor = 2;
}

message BuyResourcesRequest {
}

message BuyResourceDTO {
  string wanted_resource = 1;
  string buy_with_resource = 2;
  int64 amount = 3;
  string feature_main_type = 4;
  string context_definition_id = 5;
  UUID context_id = 6;
  int64 passive_player_id = 7;
}

message RelatedBuildingTraitDTO {
  string building = 1;
}

message CapByBuildingLimitTraitDTO {
}

message WonderBlueprintTraitDTO {
  string building_group = 1;
}

message GoodBuildingTraitDTO {
  string building = 1;
}

message WildcardTraitDTO {
  string feature = 1;
}

message GameRegeneratingTraitDTO {
  int64 max = 1;
  float amount_per_unit = 2;
  google.protobuf.Duration duration = 3;
  bool is_reset = 4;
}

message GoodTraitDTO {
  int32 good_index = 1;
}

message ResourceDeletedPush {
  string resource_definition_id = 1;
}

message QuickjumpTraitDTO {
}

message FragmentTraitDTO {
  int64 required_amount = 1;
  ResourceDataDTO converted = 2;
}

message EquivalentResourceTraitDTO {
  string resource = 1;
}
