syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/timestamp.proto";
import "uuid.proto";

message ResourceConversionComponentDTO {
  string id = 1;
  string resource = 2;
}

message ResourceConversionGroupDTO {
  string group = 1;
  int64 limit = 2;
  float factor = 3;
  ResourceConversionFilterDTO filter = 5;
  string asset_id = 6;
}

message ResourceConversionFilterDTO {
  string resource_definition_id = 1;
  string resource_type = 2;
  string city_definition_id = 3;
}

message ResourceConversionConvertRequest {
  UUID building_id = 1;
  string group = 2;
  string resource = 3;
  int64 amount = 4;
}

message ResourceConversionStateDTO {
  UUID building_id = 1;
  string resource_conversion_component_id = 2;
  string group = 3;
  google.protobuf.Timestamp today_start = 4;
  int64 converted_today = 5;
  google.protobuf.Timestamp dto_timestamp = 6;
}

message ConvertResourceTaskDTO {
  string id = 1;
  int64 amount = 2;
  string output_resource = 3;
}
