syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "building.proto";
import "expansion_type.proto";
import "google/protobuf/any.proto";
import "google/protobuf/duration.proto";
import "init.proto";
import "rarity.proto";
import "worker.proto";

enum FixedRewardStrategy {
  FixedRewardStrategy_Wonder = 0;
}

message RewardDefinitionDTO {
  string id = 1;
  bool rewards = 2;
  bool components = 3;
  bool hidden = 4;
  BaseRewardDTO base_data = 5;
}

message RewardsReceivedResponse {
  string rewards = 2;
  string feature = 3;
}

message RewardsReceivedDTO {
  string feature = 1;
  string display_id = 2;
  RandomSeedInfoDTO rewards = 3;
  RandomSeedInfoDTO random_seed = 4;
}

message ReceivedRewardDTO {
  google.protobuf.Any reward = 1;
  string parents = 2;
  string source = 3;
}

message ReceivedRewardParentDTO {
  string reward_id = 1;
  RandomSeedInfoDTO seed_info = 2;
}

message RandomSeedInfoDTO {
  int64 seed = 1;
}

message BaseRewardDTO {
  string id = 1;
  bool hidden = 2;
  google.protobuf.Any requirements = 3;
  google.protobuf.Any replacement_reward = 4;
  Rarity rarity = 5;
}

message IncreaseBuildingLimitRewardDTO {
  BaseRewardDTO base_data = 1;
}

message ChangeBuildingLimitByTypeDTO {
  string type = 1;
  int32 amount = 2;
  bool remove = 3;
}

message ChangeBuildingLimitByGroupDTO {
  string group = 1;
  string resource = 2;
  int32 amount = 3;
  bool remove = 4;
}

message UnlockBuildingRewardDTO {
  BaseRewardDTO base_data = 1;
}

message UnlockBuildingUpgradeRewardDTO {
  BaseRewardDTO base_data = 1;
}

message UnlockGoodRewardDTO {
  BaseRewardDTO base_data = 1;
  string cities = 2;
  string age = 3;
}

message UnlockQuestlineRewardDTO {
  BaseRewardDTO base_data = 1;
}

message CompleteQuestRewardDTO {
  string questline_definition_id = 1;
  string quest_component_definition_id = 2;
  BaseRewardDTO base_data = 3;
}

message IncreaseExpansionRightRewardDTO {
  BaseRewardDTO base_data = 1;
  string city = 2;
  int32 regular = 3;
  int32 premium = 4;
  ExpansionSubType sub_type = 5;
}

message UnlockAgeRewardDTO {
  BaseRewardDTO base_data = 1;
}

message LootContainerRewardDTO {
  BaseRewardDTO base_data = 1;
  string rewards = 2;
  string asset_id = 3;
}

message MysteryChestRewardDTO {
  BaseRewardDTO base_data = 1;
  string rewards = 2;
  string chances = 3;
  string asset_id = 5;
  string components = 6;
  string random_seed_counter = 7;
}

message ResourceRewardDTO {
  BaseRewardDTO base_data = 1;
  string resource = 2;
  int64 amount = 3;
  bool from_resource_change = 4;
}

message SeasonPassPremiumLaneRewardDTO {
  BaseRewardDTO base_data = 1;
  string event = 2;
  string group = 3;
}

message UnitRewardDTO {
  BaseRewardDTO base_data = 1;
  string unit = 2;
  int32 amount = 3;
}

message InstantUpgradeRewardDTO {
  BaseRewardDTO base_data = 1;
  string target = 2;
  bool auto_finish = 4;
  google.protobuf.Duration duration = 5;
  ActionComponentDTO start = 7;
  ActionComponentDTO complete = 8;
  string source = 9;
  string source_group = 10;
  bool cities = 11;
  bool uses_construction_slots = 12;
}

message UnlockCityRewardDTO {
  BaseRewardDTO base_data = 1;
  string city = 2;
}

message WorkerRewardDTO {
  BaseRewardDTO base_data = 1;
  string city = 2;
  WorkerType type = 3;
  int32 amount = 4;
}

message ActivateShopOfferRewardDTO {
  BaseRewardDTO base_data = 1;
  string offer_id = 2;
  google.protobuf.Duration active_duration = 3;
  int32 purchase_limit = 4;
}

message EventDailySpecialRewardDTO {
  BaseRewardDTO base_data = 1;
  string event_definition_id = 2;
}

message DynamicActionChangeRewardDTO {
  BaseRewardDTO base_data = 1;
  string dynamic_definition_id = 2;
  int32 amount = 3;
}

message GoodRewardDTO {
  int32 offset = 1;
  int32 number = 2;
  int32 amount = 3;
}

message BuildingAgeUpgradeRewardDTO {
  BaseRewardDTO base_data = 1;
}

message DailyEconomyBoostRewardDTO {
  BaseRewardDTO base_data = 1;
}

message FixedRewardComponentDTO {
  string id = 1;
  FixedRewardStrategy strategy = 2;
  string required_entity = 3;
  string reward_id = 4;
}

message SelectionKitRewardDTO {
  BaseRewardDTO base_data = 1;
  string selection_kit = 2;
  int32 amount = 3;
}

message UnlockExpansionRewardDTO {
  BaseRewardDTO base_data = 1;
  string expansion = 2;
}

message InstantExpansionConstructionUnlockedRewardDTO {
  BaseRewardDTO base_data = 1;
  string construction_component_id = 2;
  string city = 3;
}

message WonderPromotionComponentDTO {
  string id = 1;
  Rarity rarity = 2;
  int32 promoted_chance = 3;
  int32 not_promoted_chance = 4;
  int32 promoted_with_guaranteed_pull_chance = 5;
  int32 not_promoted_with_guaranteed_pull_chance = 6;
  string collection_id = 7;
}

message IncreaseBazaarOfferSlotsRewardDTO {
  BaseRewardDTO base_data = 1;
  int32 amount = 2;
  string bazaar_definition_id = 3;
}

message IncreaseBazaarLevelRewardDTO {
  BaseRewardDTO base_data = 1;
  int32 amount = 2;
  string bazaar_definition_id = 3;
}

message UnlockBazaarRewardDTO {
  BaseRewardDTO base_data = 1;
  string bazaar_definition_id = 2;
}

message NegotiationTurnRewardDTO {
  BaseRewardDTO base_data = 1;
}

message PlaceConstructedBuildingRewardDTO {
  BaseRewardDTO base_data = 1;
  string building_definition_id = 2;
  int32 x = 3;
  int32 y = 4;
  BuildingRotationType rotation = 6;
  string city_definition_id = 7;
}

message SkipConstructionUpgradeRewardDTO {
  BaseRewardDTO base_data = 1;
}

message SkipProductionRewardDTO {
  BaseRewardDTO base_data = 1;
}

message StorageCapRewardDTO {
  BaseRewardDTO base_data = 1;
  string resource_definition_id = 2;
  int64 amount = 3;
}

message EquivalentRewardDTO {
  BaseRewardDTO base_data = 1;
  string equivalent_resource_definition_id = 2;
  float equivalent_resource_amount = 3;
  string output_resource_definition_id = 4;
}

message RelicStatsIncreaseRewardDTO {
  BaseRewardDTO base_data = 1;
  float amount = 2;
}
