syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/timestamp.proto";
import "init.proto";

message GetShopRequest {
}

message ShopContentChangedDTO {
}

message ShopDTO {
  OneTimeBonusDTO mobile_product_ids = 3;
  OneTimeBonusDTO one_time_bonus = 4;
}

message ShopTabDTO {
  string id = 1;
  string pages = 2;
  string shop = 3;
}

message ShopPageDTO {
  string id = 1;
  string offers = 2;
  string layout_id = 3;
  string background_id = 4;
}

message ShopOfferDTO {
  string offer_id = 1;
  string type = 2;
  string product_id = 3;
  string payload = 4;
  string feature_main_type = 5;
  string feature_sub_type = 6;
  ActionComponentDTO action = 7;
  string signature = 8;
  google.protobuf.Timestamp expires_at = 9;
  int32 purchases_left = 10;
  bool popular = 11;
  bool best_deal = 12;
  int32 original_premium_amount = 13;
  int32 bonus = 14;
  string icon = 15;
  int32 purchases_limit = 16;
  string purchases_limit_group = 17;
  string group_id = 19;
  bool always_active = 20;
  ShopOfferActiveBonusDTO active_bonus = 21;
  string focus_reward_id = 22;
  string focus_background = 23;
  bool include_focus_reward_in_list = 24;
  string subscription_benefit_definition_ids = 25;
  string crm_target_id = 26;
  string crm_content_id = 27;
  int32 callout_priority = 28;
  bool visible_when_purchase_limit_reached = 29;
  int32 order = 30;
  Struct frontend_defined_values = 31;
  google.protobuf.Timestamp offer_components = 32;
  google.protobuf.Timestamp valid_from = 33;
  google.protobuf.Timestamp valid_until = 34;
  bool is_browser_offer = 35;
  bool visibility_requirements = 36;
  bool require_custom_signature = 37;
  int32 revenue_used_percentage = 38;
}

message ShopOfferGroupDefinitionDTO {
  string id = 1;
  string quest_giver = 2;
  string background = 3;
}

message ModularOfferHeroViewDTO {
  string hero_definition_id = 1;
  int32 scale = 2;
  bool mirrored = 3;
}

message ShopPurchasedDTO {
  string transaction_id = 1;
  string product = 2;
  string payload = 3;
  string offer_id = 4;
  int64 received_rewards = 5;
  int64 premium_amount = 6;
  string currency = 7;
  int32 price_in_cents = 8;
}

message OneTimeBonusDTO {
  int32 percent = 1;
  google.protobuf.Timestamp expires_at = 2;
}

message ShopOfferActiveBonusDTO {
  int32 bonus_percent = 1;
  int32 bonus_amount = 2;
  google.protobuf.Timestamp expires_at = 3;
  string expires_at_formatted = 4;
}

message BrowserShopUrlResponse {
  string url = 1;
}

message SubscriptionsDTO {
}

message SubscriptionDTO {
  string product_id = 1;
  string status = 2;
  bool is_entitled = 3;
  google.protobuf.Timestamp valid_from = 4;
  google.protobuf.Timestamp valid_to = 5;
  bool is_auto_renewing = 6;
}

message InGameShopBuyRequest {
  string in_game_shop_offer_definition_id = 2;
  int32 amount = 3;
}

message ProductSlotsResponse {
}

message ShopPurchaseDisplayedRequest {
  string transaction_id = 1;
}

message BuyShopOfferTaskDTO {
  string id = 1;
  int64 amount = 2;
}
