syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/timestamp.proto";

message StartupRequest {
}

message StartupResponse {
  string server_version = 1;
  google.protobuf.Timestamp server_time = 2;
}

message GameDesignRequest {
  string checksum = 1;
}

message GameDesignResponse {
  string checksum = 1;
}

message GameDesignUpdatedPush {
}

message GameDesignReference {
  string id = 1;
  string dto_type_url = 2;
}

message WakeupResponse {
  google.protobuf.Timestamp server_time = 1;
}
