syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
import "init.proto";
import "resource.proto";

message PoolTaskListDTO {
}

message PoolTaskDeletedPush {
  int64 pool_task_id = 1;
}

message PoolTaskDTO {
  int32 player_id = 1;
  string progress = 2;
  string selector = 3;
  string task_pool_entry_id = 4;
  int64 pool_task_id = 5;
  int64 selector_id = 6;
}

message TaskPoolSelectorDefinitionDTO {
  string id = 1;
  string pool_definition_id = 2;
  string trait = 3;
  bool stacking = 4;
  string interval = 5;
  int32 weights = 6;
  int32 amount = 7;
  string type = 8;
  string feature_main_type = 9;
  google.protobuf.Duration cooldown = 10;
}

message TaskPoolDefinitionDTO {
  string id = 1;
}

message TaskPoolEntryComponentDTO {
  string id = 1;
  bool or_condition = 2;
  ActionComponentDTO requirements = 4;
  ActionComponentDTO traits = 5;
  ActionComponentDTO finish = 6;
}

message CollectTaskRequest {
  int64 pool_task_id = 2;
  ExpectedTaskProgressionDTO expected_progress = 3;
}

message TaskPoolNegotiationLocationDTO {
  int64 pool_task_id = 1;
  string task_id = 2;
}

message ExpectedTaskProgressionDTO {
}

message TaskPoolBattleLocationDTO {
  int64 pool_task_id = 1;
  string task_id = 2;
}

message TaskPoolEventComponentDTO {
  string id = 1;
}

message TaskPoolEventStateDTO {
  message TaskPoolSelectorDTO {
    int64 id = 1;
    google.protobuf.Timestamp last_trigger_time = 2;
  }
}

message PartialPayTaskPoolTaskRequest {
  string task_id = 2;
  int64 pool_task_id = 3;
  ResourceDTO invest_resource = 5;
  int64 invested_premium = 6;
  PartialPaymentType partial_payment_type = 7;
}
