syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "init.proto";

message FinishTutorialRequest {
  string tutorial_key = 1;
}

message ResetTutorialRequest {
  string tutorial_key = 1;
}

message TutorialConstantsDefinitionDTO {
  string tutorial_battle_questline_id = 3;
  string tutorial_support_units_encounter_id = 4;
  string tutorial_hero_level_encounter_id = 5;
  string tutorial_rift_id = 6;
  string tutorial_rewards = 7;
  string tutorial_rift_questline_id = 8;
  string tutorial_research_questline_id = 9;
  string tutorial_foundations_questline_id = 10;
  string tutorial_support_units_questline_id = 11;
  string tutorial_hero_level_questline_id = 12;
  string tutorial_naya_recover_encounter_id = 13;
  string tutorial_expansion_questline_id = 14;
  string tutorial_heroes = 15;
  string tutorial_expansion_encounter_id = 16;
  string tutorial_auto_battle_encounter_id = 17;
  string tutorial_culture_questline_id = 18;
}

message TutorialRewardDTO {
  string tutorial_key = 1;
  ActionComponentDTO reward = 2;
  string base_tutorial_key = 3;
  object building_group = 10;
  object building_definition_id = 11;
}

message TutorialHeroInBattleDTO {
  string tutorial_key = 1;
  string battle_definition_id = 2;
  string hero_definition_id = 3;
  string star_up_definition_id = 4;
}
