syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
import "init.proto";
import "worker.proto";

message UpgradeDTO {
  int64 id = 1;
  string definition_id = 2;
  bool started = 3;
  google.protobuf.Timestamp started_at = 4;
  bool completed = 5;
  google.protobuf.Timestamp complete_at = 6;
}

message UpgradeComponentDTO {
  string id = 1;
  string target = 2;
  bool auto_finish = 4;
  google.protobuf.Duration duration = 5;
  ActionComponentDTO start = 7;
  ActionComponentDTO complete = 8;
  ActionComponentDTO finish = 9;
  RequiredWorkersDTO workers_required = 10;
  bool uses_construction_slots = 11;
}

message LevelUpComponentDTO {
  string id = 1;
  google.protobuf.Duration duration = 2;
  ActionComponentDTO start = 4;
  RequiredWorkersDTO star_levels = 6;
  RequiredWorkersDTO workers_required = 7;
  bool uses_construction_slots = 8;
}
