syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/any.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

message VideoRewardDefinitionDTO {
  string definition_id = 1;
  string placement = 2;
  bool discardable = 3;
  int32 max_per_day = 4;
  google.protobuf.Duration cooldown = 5;
}

message VideoRewardDTO {
  int64 id = 1;
  string video_reward_definition_id = 2;
  google.protobuf.Timestamp valid_from = 3;
  google.protobuf.Timestamp valid_until = 4;
  bool watched = 5;
  bool granted = 6;
  bool dismissed = 7;
  google.protobuf.Any data = 8;
}

message VideoRewardStateDTO {
  string video_reward_definition_id = 1;
  VideoRewardDTO active_video = 2;
  int32 remaining_today = 3;
  int32 watched_today = 4;
  google.protobuf.Timestamp today_started_at = 5;
  google.protobuf.Timestamp last_watched_at = 6;
}

message VideoLoadedResponse {
}

message VideoDismissRequest {
  int64 video_reward_id = 1;
}

message VideoDismissResponse {
  int64 video_reward_id = 1;
}

message VideoWatchedRequest {
  int64 video_reward_id = 1;
  string ad_provider = 2;
}

message VideoWatchedResponse {
  int64 video_reward_id = 1;
}

message VideoRewardStatesResponse {
}

message SeeVideoAvailableRequest {
  int64 video_reward_id = 1;
}

message StartWatchingVideoRequest {
  int64 video_reward_id = 1;
}

message VideoNotAvailableRequest {
  int64 video_reward_id = 1;
  string reason = 2;
}

message FailedWatchingVideoRequest {
  int64 video_reward_id = 1;
  int64 error_id = 2;
}

message DailyEconomyBoostsResponse {
}

message DailyEconomyBoostPushDTO {
  string component_definition_id = 1;
  google.protobuf.Timestamp started_at = 2;
  google.protobuf.Timestamp ended_at = 3;
}

message DailyEconomyBoostsCleanedPushDTO {
}
