syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";
import "hero_battle.proto";
import "ingame_event.proto";
import "init.proto";
import "player.proto";

enum WoAPoiSlotStateDTO {
  EMPTY = 0;
  GARRISONED = 1;
  GARRISONED_NPC = 2;
  BREACHED = 3;
  REPAIRING = 4;
  REPAIRED_SHIELD = 5;
  REPAIRED_SHIELD_GARRISONED = 6;
  ABANDONED = 7;
}

enum WoABattleLogTypeDTO {
  UNKNOWN = 0;
  DAMAGED_ENEMIES = 1;
  SLOT_BREACHED = 2;
  DEFENSE_WON = 3;
  SLOT_BREACHED_DEFENSE = 4;
  SLOT_GARRISONED = 5;
  HEALED_HEROES = 6;
  REPAIR_STARTED = 7;
  POI_CAPTURED = 8;
  POI_LOST = 9;
  SLOT_WITHDRAWN = 10;
}

message WoAUseHealingItemsRequest {
  int64 event_id = 1;
  google.protobuf.Timestamp expected_version_slot = 4;
  google.protobuf.Timestamp expected_version_poi = 5;
  int64 division_id = 10;
  string item_definition_id = 13;
}

message WoAWithdrawSquadRequest {
  int64 event_id = 1;
  google.protobuf.Timestamp expected_version_slot = 2;
  google.protobuf.Timestamp expected_version_poi = 3;
  int64 division_id = 10;
  int32 poi_index = 11;
  int32 slot_id = 12;
}

message WoAGarrisonRequest {
  int64 event_id = 1;
  google.protobuf.Timestamp expected_version_poi = 2;
  google.protobuf.Timestamp expected_version_roster = 3;
  int64 division_id = 10;
  int32 poi_index = 11;
  int32 slot_id = 12;
}

message WoAReinforceRequest {
  int64 event_id = 1;
  google.protobuf.Timestamp expected_version_poi = 2;
  google.protobuf.Timestamp expected_version_poi_slot = 3;
  int64 division_id = 10;
  int32 poi_index = 11;
  int32 slot_id = 12;
}

message WoARepairRequest {
  int64 event_id = 1;
  google.protobuf.Timestamp expected_version_poi = 2;
  google.protobuf.Timestamp expected_version_poi_slot = 3;
  google.protobuf.Timestamp expected_version_roster = 4;
  int64 division_id = 10;
  int32 poi_index = 11;
  int32 slot_id = 12;
}

message WoASetMapMarkerRequest {
  int64 event_id = 1;
  google.protobuf.Timestamp expected_version_poi = 2;
  int64 division_id = 10;
  int32 poi_index = 11;
  string marker_definition_id = 12;
  string text = 13;
}

message WoARemoveMapMarkerRequest {
  int64 event_id = 1;
  google.protobuf.Timestamp expected_version_poi = 2;
  int64 division_id = 10;
  int32 poi_index = 11;
}

message WoAAddHeroesToRosterRequest {
  int64 event_id = 1;
}

message WoAWarEnergyRefillRequest {
  int64 event_id = 1;
  string refill_definition_id = 10;
}

message WoARefreshStateRequest {
  int64 event_id = 1;
}

message WoABattleLocationDTO {
  int64 event_id = 1;
  google.protobuf.Timestamp expected_poi_version = 2;
  google.protobuf.Timestamp expected_poi_slot_version = 3;
  google.protobuf.Timestamp expected_player_hero_roster_version = 4;
  int64 division_id = 10;
  int32 poi_index = 11;
  int32 slot_index = 12;
  int32 attacking_from_poi_index = 13;
}

message WoAAlliancePush {
  int64 event_id = 1;
  int64 alliance_id = 2;
  google.protobuf.Timestamp version = 3;
  float vp = 10;
  float vp_generation_rate = 11;
  google.protobuf.Timestamp last_vp_generation = 12;
}

message VpGenerationRateChangeDTO {
  google.protobuf.Timestamp change_time = 1;
  float rate_delta = 2;
}

message WoAPoiPush {
  int64 event_id = 1;
  int64 division_id = 2;
  int32 poi_index = 3;
  google.protobuf.Timestamp version = 4;
  string poi_definition_id = 10;
  int64 controlled_by_alliance_id = 11;
  google.protobuf.Timestamp slots = 12;
  google.protobuf.Timestamp conquered_at = 15;
  WoAMarkerDTO marker = 16;
}

message WoAMarkerDTO {
  string marker_definition_id = 1;
  google.protobuf.Timestamp marker_set_at = 2;
  int32 marker_set_by = 3;
  string text = 4;
}

message WoAPoiConqueredPush {
  int64 event_id = 1;
  int64 division_id = 2;
  int32 poi_index = 3;
  string poi_definition_id = 10;
  int64 old_owner_alliance_id = 11;
}

message WoAPoiSlotDTO {
  google.protobuf.Timestamp version = 1;
  google.protobuf.Timestamp state_set_at = 2;
  WoAPoiSlotStateDTO state = 3;
  int64 heroes = 4;
  int64 breached_by_alliance_id = 5;
  google.protobuf.Timestamp breached_at = 6;
}

message WoAStationedHeroDTO {
  int32 player_id = 1;
  string hero_definition_id = 2;
  HeroBattleHeroAndSupportUnitDTO hero_and_support_unit = 3;
  float current_hp = 4;
}

message WoAHeroRosterPush {
  int64 event_id = 1;
  int32 player_id = 2;
  google.protobuf.Timestamp version = 3;
}

message WoAHeroDTO {
  google.protobuf.Timestamp version = 1;
  string hero_definition_id = 2;
  float stored_stat_value = 3;
  google.protobuf.Timestamp regen_starting_at = 4;
  bool knocked_out = 5;
  int32 stationed_in_poi = 6;
  google.protobuf.Timestamp stationed_until = 7;
  int32 stationed_in_slot = 10;
}

message WoADivisionPush {
  int64 event_id = 1;
  int64 division_id = 2;
}

message WoAPoiDefinitionDTO {
  string id = 1;
  google.protobuf.Duration unlock_after = 2;
  google.protobuf.Duration vp_generation_interval = 3;
  float vp_generation_amount = 4;
  int32 slots = 5;
  float vp_for_victory = 6;
  float vp_for_defense_victory = 7;
  float vp_for_conquering = 8;
  string asset_id = 14;
}

message WoAMarkerDefinitionDTO {
  string id = 1;
}

message WoAPoiPositionDTO {
  WoAPoiDefinitionDTO poi = 1;
  int32 index = 2;
  int32 reachable_pois = 3;
  int32 x = 4;
  int32 y = 5;
  int32 initial_owner = 6;
  int32 asset_variant_index = 7;
  string display_id = 8;
}

message WoAMapDefinitionDTO {
  string id = 1;
  int32 poi_positions = 2;
  int32 grid_rows = 3;
  int32 grid_columns = 4;
}

message WoACpUpdatePush {
  int64 event_id = 1;
  int64 division_id = 2;
  int64 alliance_id = 4;
  int64 alliance_cp = 6;
}

message WoAPlayerCpRewardLaneComponentDTO {
  string definition_id = 1;
  InGameEventStateDTO rewards = 2;
  InGameEventStateDTO minimum_state_to_collect = 3;
}

message WoAAllianceCpRewardLaneComponentDTO {
  string definition_id = 1;
  InGameEventStateDTO rewards = 2;
  InGameEventStateDTO minimum_state_to_collect = 3;
  int32 unlock_player_cp_threshold = 4;
}

message WoADefinitionDTO {
  string id = 1;
  int32 hero_roster_size = 2;
  int32 alliances = 3;
  WoAMapDefinitionDTO map = 5;
  int32 battlefield_slot_offset = 6;
  google.protobuf.Duration conflict_phase_start = 8;
  google.protobuf.Duration conflict_phase_end = 9;
  string elo_group = 10;
  int32 starting_elo = 11;
  float unit_stat_regen = 12;
  google.protobuf.Duration unit_stat_regen_duration = 13;
  float knocked_out_regen_threshold = 14;
  google.protobuf.Duration repair_duration = 15;
  google.protobuf.Duration repair_duration_reduction = 16;
  int32 max_repairing_players = 17;
  google.protobuf.Duration repair_shield_duration = 18;
  google.protobuf.Duration conquest_shield_duration = 19;
  string battle_definition_id = 20;
  ActionComponentDTO attack_action = 21;
  ActionComponentDTO heal_action = 22;
  int32 max_attacking_alliances = 25;
  float attacker_min_battle_damage = 29;
  float defender_min_battle_damage = 30;
  int64 cp_for_attack = 31;
  int64 cp_for_conquest = 32;
  int64 cp_for_defense_victory = 33;
  int64 cp_for_healing = 34;
  int64 cp_for_repair_started = 35;
  WoAFinalRewardDefinitionDTO final_reward = 36;
  int64 reward_min_cp = 37;
}

message WoAFinalRewardDefinitionDTO {
  string resource_id = 1;
  int64 base_pool = 2;
  double scaling_factor = 3;
  int32 baseline_elo = 4;
  int64 pool_cap = 5;
}

message WoAEventPlayerStateDTO {
  int64 division_id = 1;
  int64 alliance_id = 2;
  google.protobuf.Timestamp left_alliance_at = 3;
}

message WoAMapMarkerSetChatNotificationDTO {
  int64 event_id = 1;
  int64 division_id = 2;
  int32 poi_index = 3;
  string marker_definition_id = 4;
  int32 player_id = 5;
}

message WoAConflictPhaseRequirementDTO {
  string event_definition_id = 1;
}

message WoACollectFinalRewardRequest {
  int64 event_id = 1;
}

message WoAPendingRewardPush {
  int64 event_id = 1;
  int32 alliance_rank = 2;
  int64 reward_amount = 3;
  string resource_id = 4;
  bool collected = 5;
}

message WoAGetPlayerStatsRequest {
  int64 event_id = 1;
}

message WoAGetPlayerStatsResponse {
}

message WoAPlayerStatsDTO {
  PlayerInfoDTO player = 1;
  float victory_points = 2;
  int32 won_attacks = 3;
  int32 won_defenses = 4;
  int32 repairs_started = 5;
  int64 contribution_points = 6;
  int64 event_id = 7;
  google.protobuf.Timestamp contribution_points_gained_at = 8;
  int32 healing_done = 9;
  int32 lost_attacks = 10;
}

message WoAHealingItemTraitDTO {
  float healing_amount = 1;
  bool knocked_out = 2;
}

message WoAHealHeroTargetDTO {
  string target_hero_id = 1;
  google.protobuf.Timestamp expected_version_target_hero = 2;
}

message WoAHealRosterTargetDTO {
  int32 target_player_id = 1;
  google.protobuf.Timestamp expected_version_target_roster = 2;
}

message WoABattleLogRequest {
  int64 event_id = 1;
  google.protobuf.Timestamp before = 2;
  int32 page_size = 3;
}

message WoABattleLogResponse {
}

message WoABattleLogEntryDTO {
  int64 id = 1;
  google.protobuf.Timestamp created_at = 2;
  WoABattleLogTypeDTO log_type = 3;
  int32 player_id = 4;
  int32 poi_index = 5;
}

message WoABattleLogEntryPush {
  int64 event_id = 1;
  int64 alliance_id = 2;
  WoABattleLogEntryDTO entry = 3;
}
