syntax = "proto3";

package InnoGames.Generated.Protobuf;

import "google/protobuf/timestamp.proto";
import "uuid.proto";

enum WorkerType {
  WorkerType_CITY = 0;
  WorkerType_PRIEST_MAYA = 1;
  WorkerType_SAILOR_VIKINGS = 2;
}

enum WorkerLocationType {
  WorkerLocationType_BUILDING = 0;
  WorkerLocationType_EXPANSION = 1;
  WorkerLocationType_INCIDENT = 2;
  WorkerLocationType_WONDER = 3;
}

enum GrantWorkerSource {
  GrantWorkerSource_BUILDING_CONSTRUCTION = 0;
  GrantWorkerSource_BUILDING_UPGRADE = 1;
  GrantWorkerSource_REWARD = 2;
  GrantWorkerSource_BUILDING_AGE_UPGRADE = 3;
  GrantWorkerSource_WONDER_ACTIVATION = 4;
  GrantWorkerSource_WONDER_UPGRADE = 5;
}

message WorkerDTO {
  UUID id = 1;
  WorkerType type = 2;
  WorkerLocationDTO location = 3;
  google.protobuf.Timestamp release_at = 4;
}

message WorkerLocationDTO {
  WorkerLocationType type = 1;
  UUID id = 2;
  int64 numeric_id = 3;
}

message WorkersPush {
  int64 city_id = 1;
}

message PrepareableWorker {
  UUID id = 1;
  WorkerType type = 2;
}

message RequiredWorkersDTO {
  int32 amount = 1;
  WorkerType type = 2;
  string dynamic_value_definition_id = 3;
}

message PrepareGrantWorkerRequest {
  GrantWorkerSource worker_ids = 2;
  GrantWorkerSource source = 3;
  UUID source_building_id = 4;
  string source_reward_id = 5;
  UUID preparable_workers = 6;
  UUID source_wonder_id = 7;
}
